### ISSUE TITLE
[Template] Appsettings contains incorrect section for Localization

### ISSUE THREAD

**Issue by nickrandolph** [unoplatform/uno.extensions#1049]
## Current behavior

Appsettings includes section called LocalizationSettings. 
## Expected behavior

The Appsettings section should should be LocalizationConfiguration

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by dansiegel** [comment]
fixed by #1050
