### ISSUE TITLE
[Template] Resw files aren't correctly referenced as PRIResources

### ISSUE THREAD

**Issue by nickrandolph** [unoplatform/uno.extensions#1051]
## Current behavior

Build action for resw files is set to None

## Expected behavior

Build action should be set to PRIResource

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by dansiegel** [comment]
fixed by #1050
