### ISSUE TITLE
[Navigation][Android] Is it possible to display a dialog that can't be dismissed by the native back button?

### ISSUE THREAD

**Issue by takla21** [unoplatform/uno.extensions#1103]
## Current behavior
When we display a custom dialog with uno.extension navigation, you can always dismiss it by pressing the native back button. 

## Expected behavior
Ideally have a way to setup when displaying the dialog to never being able to dismissed it.

## How to reproduce it (as minimally and precisely as possible)

- Create a new project from uno.extensions template
- Add a content dialog and use Uno.extensions.navigation to display it

## Environment

Nuget Package: uno.extensions

Package Version(s): 2.3.0-dev.506 (the one we're currently using on our project)

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by francoistanguay** [comment]
Have you tried cancelling the request in Closing event of the ContentDialog?

**Comment by takla21** [comment]
@francoistanguay No I haven't. I'll try asap

**Comment by takla21** [comment]
For update, I tried to set the `Cancel` property to true when the `Closing` event is raised. It works for most of the part. However, when you put the app in background, it will still close the ContentDialog even if the event is raised and that we set the property.

**Comment by jeromelaban** [comment]
@takla21 We changed a behavior for the back button recently. Could you take a look at this in your canaries?

**Comment by nickrandolph** [comment]
@takla21 can you confirm that this is still an issue

**Comment by nickrandolph** [comment]
@takla21 do you know whether this is still an issue?

**Comment by takla21** [comment]
@nickrandolph Sorry for the late response. No, it's not really an issue for us at this time. We can close this for now
