### ISSUE TITLE
New solution from unoapp-extensions doesn't show Android emulators 

### ISSUE THREAD

**Issue by ttustonic** [unoplatform/uno.extensions#1106]
## Current behavior
New solution created using unoapp-extension template doesn't show a list of installed Android emulators.
![ext](https://user-images.githubusercontent.com/5532089/214415304-59e46b39-3f4b-4060-8aba-be9b170751a4.jpg)

Solutions created from Visual studio new Uno Platform App or from unoapp template look fine
![uno](https://user-images.githubusercontent.com/5532089/214415378-955d96f7-35c7-45c1-895d-0a7a92951211.jpg)

Extensions app runs fine in first installed Android emulator, but it can't be changed.

Xamarin Diagnostics log is the same for both projects, and it can find device(s):
[I:]:                     Tracking android devices stopped
[I:]:                     Tracking android devices started
[D:]:                     Tracking avd started
[D:]:                     ANDROID_AVD_HOME found: E:\Android\avd
[D:]:                     avd watcher *.ini path: 'E:\Android\avd'
**[D:]:                     TrackDeviceTask got: emulator-5554	device
[I:]:                     Got new device list from adb with 1 devices**
[D:RunShellCommand]:      emulator-5554 getprop
[D:]:                     avd watcher: got device list from avd with 1 devices

## Expected behavior

It should look and work the same as the project from unoapp template

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ x] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2022 (version: 17.4.4)
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

[ExtTest.zip](https://github.com/unoplatform/uno.extensions/files/10494087/ExtTest.zip)

**Comment by nickrandolph** [comment]
Which version of the unoapp-extensions template are you using? If possible can you update to the latest dev version and give that a go

**Comment by ttustonic** [comment]
Yes, it looks ok with version 2.3.0-dev.584.
Btw, I like the new options for the template.
Thanks, Tom

**Comment by ttustonic** [comment]
Is there a way to fix an old project, built with template 2.2.0? I tried to compare .sln and .csproj files, but couldn't find the cause..._

**Comment by nickrandolph** [comment]
For an old project I would probably compare it to a new project created with the stable unoapp template (get the 4.6.x version from here https://www.nuget.org/packages/Uno.ProjectTemplates.Dotnet/4.6.41). You should be able to look at the mobile project and compare imports/properties
