### ISSUE TITLE
[Logging] Serilog should be nested under UseLogging

### ISSUE THREAD

**Issue by nickrandolph** [unoplatform/uno.extensions#1134]
Current template has Serilog as separate line in host builder:
https://github.com/unoplatform/uno.extensions/blob/bfb6f0a1e468c8925828885fe8b0e39130cbb367/src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp/AppStart.cs#L41

Serilog should be nested within UseLoggin

**Comment by dansiegel** [comment]
closed by #1130
