### ISSUE TITLE
Toolkit's LoadingView finishes loading while the FeedView is still loading.

### ISSUE THREAD

**Issue by Marc-Antoine-Soucy** [unoplatform/uno.extensions#1150]
## Current behavior

![LoadingViewTooSoon](https://user-images.githubusercontent.com/90481654/217822887-4c6a7c07-9be0-4d86-afd6-0c10862a2c70.gif)

Here, the red screen is the LoadingView loading template, and the blue screen is the feed's loading template

## Expected behavior

The LoadingView's loading template should stay on until the feed has finished loading.

## How to reproduce it (as minimally and precisely as possible)
Put a FeedVIew into a loading view, notice that the loading of the feedview continues even after the loadingview's loading state is gone. 

[LoadingFeedView.zip](https://github.com/unoplatform/uno.extensions/files/10697519/LoadingFeedView.zip)

## Environment

Nuget Package:
Toolkit/ reactive extension.
Package Version(s):
```
    <PackageReference Include="Uno.Extensions.Reactive.WinUI" Version="2.3.0-dev.650" />
    <PackageReference Include="Uno.Toolkit.WinUI" Version="2.5.0-dev.21" />
    <PackageReference Include="Uno.WinUI" Version="4.8.0-dev.225" />
    <PackageReference Include="Uno.WinUI.RemoteControl" Version="4.7.37" Condition="'$(Configuration)'=='Debug'" />
    <PackageReference Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="4.7.37" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="6.0.0" />
    <PackageReference Include="Uno.WinUI.Lottie" Version="4.7.37" />
```

Affected platform(s):

- [X] iOS
- [X] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [X] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [X] 2022 (version: Version 17.4.4)
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?
I'm not 100% sure if the problem is with toolkit or feedviews, so I put this here. I'm also not 100% sure if it could be an issue with my style, but I think it's important to note that without the loading state on the feedview, you just get a blank screen for a moment between the moment the loadingView is done and the feedview's content appears.

**Comment by nickrandolph** [comment]
@dr1rrb I've assigned this to you but if it's not related to FeedView just assign it back to me
