### ISSUE TITLE
The UI Test not pass with success

### ISSUE THREAD

**Issue by rafael-rosa-knowcode** [unoplatform/uno.extensions#1270]
## What would you like to be added:

I would like to test the project for UI tests.
So that it is possible to run the project with the sample test.

But i get the message. And the APP is null.

	System.NullReferenceException : Referência de objeto não definida para uma instância de um objeto.
	TearDown : System.NullReferenceException : Referência de objeto não definida para uma instância de um objeto.

![image](https://user-images.githubusercontent.com/116665025/224827488-fef2807b-135c-40a2-9490-49a146bf0f48.png)

## Why is this needed:

For show how test a UI project

## For which Platform:

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

**Comment by nickrandolph** [comment]
@rafael-rosa-knowcode I think your issue is that the url for the wasm application doesn't match what's in the constants.cs file in the uitests project. Try:
- Right click WASM project and select Debug -> Start without debugger
- Take note of the url, including port number that the wasm app launches to
- Update WebAssemblyDefaultUri in Constants.cs with the url
- Run the UI Test

**Comment by nickrandolph** [comment]
@dansiegel not withstanding the issue @rafael-rosa-knowcode  is seeing there are two issues that are preventing successful execution of the UI Test

1) Wasm csproj is missing this block - it must have been removed at some point and we failed to notice. We should really run the tests on at least one of the validation projects we create during CI.

```xml
	<PropertyGroup Condition="'$(Configuration)'=='Debug' or '$(IsUiAutomationMappingEnabled)'=='True'">
		<IsUiAutomationMappingEnabled>True</IsUiAutomationMappingEnabled>
		<DefineConstants>$(DefineConstants);USE_UITESTS</DefineConstants>
	</PropertyGroup>
```

2) template conditional blocks aren't being correctly processed, so are left in the Given_MainPage.cs file eg 
![image](https://user-images.githubusercontent.com/1614057/225535719-bd46c8fa-e3df-4b53-930d-81aa32efa3ce.png)
