### ISSUE TITLE
[HR] Pages modified through extension navigation are not reloading properly

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno.extensions#1299]
## How to reproduce it (as minimally and precisely as possible)

- Open an app built with the 4.8 template, make a modification in the main page XAML, save the file.
- Notice that the app returns the the initial loading screen.

Note that testing this behavior requires https://github.com/unoplatform/uno/pull/11749

## Environment

Package Version(s): 2.3.0

**Comment by nickrandolph** [comment]
This should be fixed by https://github.com/unoplatform/uno/pull/14142
