### ISSUE TITLE
How to use Uno.Extensions.Localization

### ISSUE THREAD

**Issue by FlytotheMuum** [unoplatform/uno.extensions#1307]
## On which page?
https://platform.uno/docs/articles/external/uno.extensions/doc/Overview/Localization/LocalizationOverview.html#
## What's wrong?

In **new template - Uno.Templates::4.9.0-dev.1**
 _(https://www.nuget.org/packages/Uno.Templates#)_
**Sample of localization string doesn't work at all.**

## App.cs
```
.UseLocalization()
```
## MainModel.cs
```		
Title = $"Main - {localizer["ApplicationName"]}";
```
It should be _applicationname-en_
but it's always _applicationname_

**Comment by nickrandolph** [comment]
@FlytotheMuum thanks for reporting - we're working on a fix for this

**Comment by nickrandolph** [comment]
Latest for uno.templates is here: https://github.com/unoplatform/uno.templates
The fixes for localization are in both Uno and extensions, so you should be able to move to latest dev libraries for these fixes.
