### ISSUE TITLE
[Reactive] FeedView.ProgressTemplate overlapping over content

### ISSUE THREAD

**Issue by weitzhandler** [unoplatform/uno.extensions#1318]
## Current behavior

Loading template on the `FeedView` appears to be overlapping.

## Expected behavior

The value template should hide while awaiting data.

## How to reproduce it (as minimally and precisely as possible)

https://github.com/unoplatform/uno.extensions/tree/f970ae4cff38180f6cf9949f2740525d30549edf/samples/MvuxHowTos/MvuxHowTos/WeatherApp

```xaml
<Page
	x:Class="WeatherApp.MainPage"
	xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
	xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
	xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
	xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
	xmlns:mvux="using:Uno.Extensions.Reactive.UI">

	<mvux:FeedView Source="{Binding CurrentWeather}">
		<DataTemplate>
			<StackPanel>
				<TextBlock DataContext="{Binding Data}" Text="{Binding Temperature}" />
				<Button Content="Refresh" Command="{Binding Refresh}" />
			</StackPanel>
		</DataTemplate>
		<mvux:FeedView.ProgressTemplate>
			<DataTemplate>
				<TextBlock Text="Requesting temperature..."/>
			</DataTemplate>
		</mvux:FeedView.ProgressTemplate>
	</mvux:FeedView>
</Page>
```

When data is loaded here's what's displayed:

![image](https://user-images.githubusercontent.com/2716316/227067193-ccf3b527-d22b-47ba-8541-ee4d0a3ebf0c.png)

**Furthermore**, the Refresh button is not responding, perhaps hidden by the other layer.

## Environment

Nuget Package:

Uno.Extensions.Reactive.WinUI

Package Version(s):

2.3.2

Affected platform(s): (only checked Windows)

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [x] Windows
- [ ] Build tasks

## Anything else we need to know?

This is a regression that started with 4.8, it used to work before.

**Comment by nickrandolph** [comment]
@dr1rrb is this by design to allow for progress indicator when there's already data loaded?

**Comment by weitzhandler** [comment]
Also there was a default progress template with "Loading...", I think it makes a lot of sense to have that template by default and let user override if they want to customize. Also default for Empty, Error etc.

**Comment by dr1rrb** [comment]
Hum definitely not by design ... probably an issue with the default style we have embedded in the assembly. Will try to have a look as I already have a pending issue to investigate about `FeedView` and loading state ^^
