### ISSUE TITLE
[WASM] Address bar change has a very noticeable delay

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno.extensions#1375]
## Current behavior

The delay in update of address bar is quite noticeable and distracting to the user (you are navigated and start viewing content and suddenly there is something changing above which forces you to move eyes for a split second at least)

![delaynavigation](https://user-images.githubusercontent.com/1075116/230768878-1eb9ddbc-6437-4427-951e-5f5e805d9a06.gif)

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by nickrandolph** [comment]
This is fixed
