### ISSUE TITLE
[Reactive] AsyncPaginatedByCursor enable null first page

### ISSUE THREAD

**Issue by weitzhandler** [unoplatform/uno.extensions#1397]
The current signature of the `AsyncPaginatedByCursor` method is [as follows](https://github.com/unoplatform/uno.extensions/blob/main/src/Uno.Extensions.Reactive/Core/ListFeed.T.cs#L92):

```c#
public static IListFeed<T> AsyncPaginatedByCursor<TCursor>(TCursor firstPage, GetPage<TCursor, T> getPage)
```

## What would you like to be added:

I'd like the `firstPage` parameter to be changed to `TCursor?`, as well as the first input parameter of the [`GetPage` delegate](https://github.com/unoplatform/uno.extensions/blob/ebb57a31da4f353f5f7265cd99e86f6b30b7b917/src/Uno.Extensions.Reactive/Sources/PageResult.cs#L17).

## Why is this needed:

The first cursor is normally not known when loading the page and starting off the pagination and cannot always be provided. It should allow a null cursor and return first page if this is the case.

**Comment by dr1rrb** [comment]
This will most probably cause some trouble with type inference, you will have to define the type of the cursors and the items. Not sure it would be easier.

**Comment by weitzhandler** [comment]
Yup, that would require either `(TCursor?)null` or `default(TCursor?)` when `TCursor` is a reference type.
I think the most common scenario would be string, which in case an empty string can be passed in. I'm therefore going to close this issue.
