### ISSUE TITLE
Question: 'MemberNotNullWhenAttribute' exists in both Uno.Extensions.Hosting and Uno.Extensions.Localization

### ISSUE THREAD

**Issue by get-flat** [unoplatform/uno.extensions#1408]
### Current behavior

1) Create a new project using Wizard
2) In the common project (UnoApp1) use [MemberNotNullWhen]

`error CS0433: The type 'MemberNotNullWhenAttribute' exists in both 'Uno.Extensions.Hosting, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' and 'Uno.Extensions.Localization, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null'`

Is this expected?

### Works on UWP/WinUI

None

**Comment by nickrandolph** [comment]
@get-flat can you confirm if this has been fixed?
