### ISSUE TITLE
[Reactive] Add support for pagination with parameters (to use with search for example)

### ISSUE THREAD

**Issue by agneszitte** [unoplatform/uno.extensions#1410]
## What would you like to be added:

Add support for pagination with parameters (to use with search for example)

## Why is this needed:

To be able to use pagination when doing a search for example in the TubePlayer project on the MainPage

## For which Platform:

- [X] All platforms

**Comment by weitzhandler** [comment]
How do we listen to several Feeds simultaneously? This way we can combine the SearchTerm and the PageIndex States and update output Feed with result from service with parameters from these two States.

For example in Rx.NET we have the [`CombineLatest`](https://learn.microsoft.com/en-us/previous-versions/dotnet/reactive-extensions/hh211991(v=vs.103)), [`Zip`](https://learn.microsoft.com/en-us/previous-versions/dotnet/reactive-extensions/hh244275(v=vs.103)), [`Concat`](https://learn.microsoft.com/en-us/previous-versions/dotnet/reactive-extensions/hh229289(v=vs.103)), [`Merge`](https://learn.microsoft.com/en-us/previous-versions/dotnet/reactive-extensions/hh229740(v=vs.103)).

How can we achieve these with Feeds/States?

**Comment by agneszitte** [comment]
@dr1rrb, @jeromelaban, @nickrandolph, @weitzhandler, @francoistanguay 
Please check the priority of this issue for the tube project
