### ISSUE TITLE
Documentation for authenticating with cookies is empty

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno.extensions#1416]
https://github.com/unoplatform/uno.extensions/blob/539d6b0f2e61fbc2ae5d6e35a77de41cafacf5ce/doc/Learn/Tutorials/Authentication/HowTo-Cookies.md

This is deployed and linked to from other pages.

**Comment by nickrandolph** [comment]
It's also not linked to the TOC at the moment.
cc @lukeblevins can you take a look at this please
