### ISSUE TITLE
[Reactive] Enable ImplicitCommand on methods

### ISSUE THREAD

**Issue by weitzhandler** [unoplatform/uno.extensions#1457]
## What would you like to be added:

Currently, the `ImplicitCommandAttribute` can only be applied on classes or assemblies.  
Sometimes, the user would choose to disable or enable a single method only from being generated as a command, rather than an entire class.  

## Why is this needed:
This could be useful when the use wants to use [Event Binding](https://learn.microsoft.com/windows/uwp/xaml-platform/x-bind-markup-extension#event-binding).

## For which Platform:
- Agnostic

**Comment by dr1rrb** [comment]
There is a [`Command` attribute](https://github.com/unoplatform/uno.extensions/blob/main/src/Uno.Extensions.Reactive/Presentation/Commands/CommandAttribute.cs) for this. It's no longer "implicit" when you enable the explicitly set it directly on a method :)

**Comment by weitzhandler** [comment]
I take it this attribute overrides any upper `ImplicitCommand` instructions both ways (on or off).
Please comment if not true.

**Comment by dr1rrb** [comment]
@weitzhandler yes the `CommandAttribute` overrides the "implicit" (in both way, to enable or disable the command generation) (cf. https://github.com/unoplatform/uno.extensions/blob/main/src/Uno.Extensions.Reactive/Config/ImplicitCommandsAttribute.cs#L11).

**Comment by weitzhandler** [comment]
https://github.com/unoplatform/uno.extensions/pull/1483
