### ISSUE TITLE
[Navigation] x:Bind doesn't work for Page

### ISSUE THREAD

**Issue by nickrandolph** [unoplatform/uno.extensions#1469]
## Current behavior

Attempt to x:Bind to a property on a viewmodel associated with a page - this fails to set the value in some cases because the DataContext is sometimes null when bindings are initialized.

## Expected behavior

x:Bind should work

## How to reproduce it (as minimally and precisely as possible)

Create new app using wizard
Pick default option and customize:
- Mvvm
- Remove Server and Http
Add ViewModel property to MainPage.xaml.cs:
`public MainViewModel? ViewModel => DataContext as MainViewModel;`
Change Binding to x:Bind in MainPage.xaml
`<utu:NavigationBar Content="{x:Bind ViewModel.Title}" />`
Add delay to MainViewModel constructor

```
        public MainViewModel(....)
        {
            ... 
            for (int i = 0; i < 2000; i++)
            {
                System.Diagnostics.Debug.WriteLine(i);
            }
        }
```

No NavigationBar Title:
![image](https://github.com/unoplatform/uno.extensions/assets/1614057/60bbd87a-8eeb-4d17-9acd-b27aac92af02)

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

Workaround - Update MainPage.xaml.cs to call Bindings.Update when DataContext changes

```
public MainPage()
{
    this.InitializeComponent();

    DataContextChanged += (_, _) => Bindings.Update();
}
```

**Comment by jeromelaban** [comment]
This is expected, and related to https://github.com/unoplatform/uno/issues/2872 and https://github.com/unoplatform/uno/issues/2895

**Comment by Youssef1313** [comment]
@jeromelaban It happens on Windows too.

**Comment by nickrandolph** [comment]
> This is expected, and related to [unoplatform/uno#2872](https://github.com/unoplatform/uno/issues/2872) and [unoplatform/uno#2895](https://github.com/unoplatform/uno/issues/2895)

Yes, it is expected but an artifact more of the way x:Bind evaluates, more than anything specifically related to the OnNavigatedTo/Loaded event sequence. In Navigation the creation of ViewModel is done on a separate thread, meaning that there could be an arbitrary delay before the view model is available and set as the DataContext. If x:Bind is evaluated before the DataContext is set, Bindings.Update needs to be invoked - this is what the fix will do.
