### ISSUE TITLE
[Reactive] CommandAttribute(isEnabled=false) not stored anywhere

### ISSUE THREAD

**Issue by weitzhandler** [unoplatform/uno.extensions#1482]
## Current behavior

The [`CommandAttribute` class](https://github.com/unoplatform/uno.extensions/blob/main/src/Uno.Extensions.Reactive/Presentation/Commands/CommandAttribute.cs#LL17C9-L17C48) reads:

```csharp
[AttributeUsage(AttributeTargets.Method)]
public class CommandAttribute : Attribute
{
    public CommandAttribute(bool isEnabled = true)
    {
    }
}
```

## Expected behavior

The parameter `isEnabled` should be stored.

**Comment by weitzhandler** [comment]
Also, inspecting the code [here](https://github.com/unoplatform/uno.extensions/blob/main/src/Uno.Extensions.Reactive.Generator/Bindables/MappedMembers/CommandFromMethod.cs#L34)

It seems it only checks if a method has this attribute completely ignoring its value.
Furthermore, if this attribute exists and its value is false, it should exit the if statement and opt-out of command generation for this method as it's been explicitly excluded.

I'm happy to PR.

**Comment by weitzhandler** [comment]
Seems this functionality works well. I also learned that those properties are not required.
Anyway, I added a test case that checks the reverse behavior of disabled implicit class and explicitly enabled method.
#1483.

**Comment by nickrandolph** [comment]
So does the current behaviour mean that [Command(false)] doesn't work to opt out of command creation?
