### ISSUE TITLE
Crash during startup on Linux with .NET 7 runtime installed

### ISSUE THREAD

**Issue by HakanL** [unoplatform/uno.extensions#1494]
## Current behavior

Crash in a new application using the new Uno template when published to Linux (Raspberry Pi) where only the .NET 7.0.5 runtime is installed. If the full SDK is installed then the application works. Exception:
```
[Logs]    [2023-05-22T15:46:58.508Z] [main] 15:46:58.506 DBG [Uno.Extensions.Hosting.Internal.Host] Hosting starting
[Logs]    [2023-05-22T15:46:58.573Z] [main] 15:46:58.571 ERR [Uno.UI.Dispatching.CoreDispatcher] Dispatcher unhandled exception
[Logs]    [2023-05-22T15:46:58.638Z] [main] System.IO.DirectoryNotFoundException: The folder  does not exist
[Logs]    [2023-05-22T15:46:58.639Z] [main]    at Windows.Storage.StorageFolder.<>c__DisplayClass52_0.<<GetFolderFromPathAsync>b__0>d.MoveNext() in /__w/1/s/src/Uno.UWP/Storage/StorageFolder.cs:line 54
[Logs]    [2023-05-22T15:46:58.639Z] [main] --- End of stack trace from previous location ---
[Logs]    [2023-05-22T15:46:58.639Z] [main]    at Windows.Foundation.AsyncOperation`1.BuildTaskAsync(FuncAsync`2 taskBuilder) in /__w/1/s/src/Uno.Foundation/Internal/AsyncOperation.TResult.cs:line 70
[Logs]    [2023-05-22T15:46:58.640Z] [main]    at System.WindowsRuntimeSystemExtensions.AsTaskCore[TResult](IAsyncOperation`1 source, CancellationToken ct) in /__w/1/s/src/Uno.UWP/System.Runtime/WindowsRuntimeSystemExtensions.cs:line 66
[Logs]    [2023-05-22T15:46:58.640Z] [main]    at Uno.Extensions.Storage.FileStorage.CreateFolderAsync(String foldername)
[Logs]    [2023-05-22T15:46:58.640Z] [main]    at Uno.Extensions.Configuration.ReloadService.StartAsync(CancellationToken cancellationToken)
[Logs]    [2023-05-22T15:46:58.640Z] [main]    at Uno.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken) in /_/src/Uno.Extensions.Hosting.UI/Internal/Host.cs:line 58
[Logs]    [2023-05-22T15:46:58.640Z] [main]    at Uno.Extensions.ServiceProviderExtensions.BuildAndInitializeHostAsync(Window window, FrameworkElement viewHost, Func`1 buildHost, String initialRoute, Type initialView, Type initialViewModel, Func`3 initialNavigate)
[Logs]    [2023-05-22T15:46:58.641Z] [main]    at Uno.Extensions.ApplicationBuilderExtensions.NavigateAsync[TShell](IApplicationBuilder appBuilder, Func`3 initialNavigate)
[Logs]    [2023-05-22T15:46:58.647Z] [main]    at DMXCore.DMXCore100.App.OnLaunched(LaunchActivatedEventArgs args) in C:\Projects\DMXCore\100\Software\Shared\App.cs:line 155
[Logs]    [2023-05-22T15:46:58.648Z] [main]    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
[Logs]    [2023-05-22T15:46:58.648Z] [main]    at Uno.UI.Dispatching.CoreDispatcherSynchronizationContext.<>c__DisplayClass3_0.<Post>b__0() in /__w/1/s/src/Uno.UI.Dispatching/Core/CoreDispatcherSynchronizationContext.cs:line 25
[Logs]    [2023-05-22T15:46:58.648Z] [main]    at Uno.UI.Dispatching.CoreDispatcher.InvokeOperationSafe(UIAsyncOperation operation) in /__w/1/s/src/Uno.UI.Dispatching/Core/CoreDispatcher.cs:line 343
```

What seems to happen is that `Windows.Storage.ApplicationData.Current.LocalFolder` is null. For some reason this gets set when the SDK is installed, no other changes (I'm running it in Docker so I can go back and forth). 

I think the [code here](https://github.com/unoplatform/uno.extensions/blob/main/src/Uno.Extensions.Hosting.UI/UnoHost.cs#L26) could be applicable for Linux as well.

## Expected behavior

No crash

## How to reproduce it (as minimally and precisely as possible)

I've used the new VS Uno template. I've made some changes to the application, but the startup should be the same. I haven't had a chance to do a complete set up from template to the Linux host (it's quite involved with Docker and everything), but it seems that the issue is consistently reproduced.

## Environment

Linux Raspberry Pi running Docker

Nuget Package: Uno.Extensions

Package Version(s): 2.3.11

Affected platform(s):

- [X] Linux Skia Framebuffer

Visual Studio:

- [X] 2022

## Anything else we need to know?

I don't know why this would be different in SDK vs runtime in .NET, it's just what I've discovered.

**Comment by nickrandolph** [comment]
cc @MartinZikmund can you check why Windows.Storage.ApplicationData.Current.LocalFolder is null on linux - can we address this with the work you're doing in this area.
@HakanL I'll look at the fix we need to do in extensions to handle null LocalFolder

**Comment by MartinZikmund** [comment]
@nickrandolph after my changes this should not happen, the AppData props should be set properly but it is going to be 5.x change

**Comment by HakanL** [comment]
I added a workaround in my start-up where I basically provide my own IDataFolderProvider that uses Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), just like the extension has for WinUI. It works fine, but obviously it would be better to not have to do that workaround.

**Comment by nickrandolph** [comment]
@HakanL can you try out the latest dev release of Uno.extensions and confirm that the [fix ](https://github.com/unoplatform/uno.extensions/pull/1496) I've posted addreses this issue?

**Comment by HakanL** [comment]
I tried to upgrade to 2.4.0-dev.329, but it opened up a can of worms on other Uno dependencies. I tried to upgrade to 2.6.0-dev.68 of Uno.Toolkit and Uno.WinUI, but I'm stuck on this issue https://github.com/unoplatform/uno.extensions/pull/1496
Is there a dependency list of what versions go together with what, it seems that some Uno components have version 2.4, some 2.5 and some 2.6?

**Comment by nickrandolph** [comment]
@HakanL can you confirm that with the latest stable release of uno we can close off this issue?
