### ISSUE TITLE
Back navigation doesn't work properly on Windows

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno.extensions#1554]
## How to reproduce it (as minimally and precisely as possible)

1. Clone this branch https://github.com/SeniorProject-2023/ocr-app/tree/nav-repro (https://github.com/SeniorProject-2023/ocr-app/commit/9b7e2f6e17ce5f9ac745afef05fe916c4b097677)

1. Open `src/UnoApp/OCRApp.sln`

1. Run OCRAp.Windows

1. Navigate to "AccountPage" (last TabBarItem)

1. Login with username "admin" and password "admin"

1. Navigate to "HomePage" (first TabBarItem)

1. Add any image from file from the FAB

1. Click "Done" from the FAB

1. Now you should be navigated to "ResultsPage", now press "Go back"

1. You are now navigated to "HomePage", but the image is gone.

1. Navigate to "AccountPage", you are now asked to login, so the "Welcome" state is gone as well.

## Expected behavior

The state isn't lost as with other Uno heads (e.g, Skia.Gtk)

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by nickrandolph** [comment]
Need to set NavigationCacheMode=Required on the page being navigated back to

**Comment by nickrandolph** [comment]
@Youssef1313 I'm going to close this as I think this was resolved. Please reopen if still an issue
