### ISSUE TITLE
[MVUX] Better support for nullability annotations

### ISSUE THREAD

**Issue by dr1rrb** [unoplatform/uno.extensions#1605]
## What would you like to be added:
`Feed.Async<T>` where `T : notnull` should accept an `AsyncFunc<T?>` and automatically interpret a `null` as `None`.

Same for other operators like `.Select`, and `.SelectAsync`.

## Why is this needed:
The language now have the nullable annotations which are commonly used by devs. Doing such would improve user experience and help to use the `None` state which is often not used.

## For which Platform:

- [x] iOS
- [x] Android
- [x] WebAssembly
- [x] WebAssembly renders for Xamarin.Forms
- [x] Windows
- [ ] Build tasks

## Anything else we need to know?
* The `Option<T>` should be hidden from "first level public API" (could be usable only with "advanced" operators)
* We already have such support for `State.Update`
* This could be a breaking change (compile time)

**Comment by nickrandolph** [comment]
@dr1rrb is this something we can get done in 5.1? If so, can you update the release number

**Comment by dr1rrb** [comment]
When we look at "operators", we have 2 cases to consider:
1. The input type parameter (`Feed.Select`; `Feed.SelectAsync`; `Feed.Where`; `State.Update`; `State.ForEachAsync`)
2. The return type (`Feed.Select`; `Feed.SelectAsync`; `State.Update`)

Case 1 could be named "None as null", while case 2 is "null as None".

# Proposal
To match the "new behavior" suggested for "factories", we should also follow the "null as None". This means that we should constraint the "return type" on all operators to `notnull` and convert the `null` to `None` (still following the feature flag).

In order to allow users to return `Some(null)` we would also have to add `.SelectData(Func<Option<TSource>, Option<TResult>>)` (using the `Data` suffix like we already have to `State.Data`), `SelectDataAsync` and `WhereData`.

However we should NOT implement the "None as null", this is to avoid to implicitly convert `None(struct)` to `Some(default(struct))` (e.g. having the "None as `null`" would allow `Feed<int>.Select(i => i + 1)` which would implicitly convert `None<int>()` to `Some(0)`)

# Special case for the State
Currently `State.Update` and `State.ForEachAsync` are already constraints to `notnull` on "input parameter". 

## State.Update
Input and output types are the same, implementing the "null as None" somehow forces us to also implement the "None as null". 

This is not as problematic as for `Feed.Select` as the `Update` is an imperative operation where we anyway expect to change the current value. Getting a default instead of `None` is actually the expected behavior.

**We suggest to keep it as-is (i.e. both "None as null" and "null as None")**

## State.ForEach
Same here, this is designed to execute imperative code, converting None to default is somehow the expected behavior. We should however add an `ForEachDataAsync` in order to allow user to make distinction between default and `None` is needed.

**We suggest to keep it as-is (i.e. both "None as null") and add `ForEachDataAsync`**

# Examples
```csharp
IState<int> intState = null!;
await intState.Update(v => v + 1); // Dangerous case: user will get 0 in case of None
await intState.Update(i => default(int?));
var intValue = await intState;

IState<MyStruct> structState = null!;
await structState.Update(v => v with { Value = 43 }); // Dangerous case: user will get default(MyStruct) in case of None
await structState.Update(v => default(MyStruct?));
var structValue = await structState;

IState<string> strState = null!;
await strState.Update(v => (v ?? "").ToString());
await strState.Update(v => default(string?));
var strValue = await strState;

IState<MyObject> objectState = null!;
await objectState.Update(v => (v ?? new(42)) with { Value = 43 });
await objectState.Update(v => default(MyObject?));
var objectValue = await objectState;
```

**Comment by dr1rrb** [comment]
To summarized the suggested changes:

* `None` as `null` (parameter value): Only for imperative operators (`State.Update`; `State.ForEachAsync`; `Feed.GetAwaiter`)
* `null` as `None` (return value): Everywhere
