### ISSUE TITLE
global using for Uno.Extensions.Toolkit should be in Uno.Extensions.Core.UI

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno.extensions#1650]
This line should be placed in `Uno.Extensions.Core.UI`:

https://github.com/unoplatform/uno.extensions/blob/27a3afd91dbd8789b24f389af0416de77ec1977f/src/Uno.Extensions.Core/build/Package.targets#L9

**Comment by nickrandolph** [comment]
It's already in `Uno.Extensions.Core` and the only classes that are in the toolkit namespace in Core.UI are internal
https://github.com/unoplatform/uno.extensions/blob/0c2d807d2943e9e61a0bf6fe69a2b3ce26a37b1f/src/Uno.Extensions.Core/build/Package.targets#L9
