### ISSUE TITLE
[Navigation] `NavigateBackWithResultAsync` processes the result but doesn't navigate back

### ISSUE THREAD

**Issue by rajamatt** [unoplatform/uno.extensions#1652]
This happens on branch [dev/mara/chore-refresh-search-page-ui](https://github.com/unoplatform/uno.chefs/tree/dev/mara/chore-refresh-search-page-ui)
Let me know if you would like me to try and create a minimal sample repro app for this issue.

## Current behavior

`NavigatorExtensions.NavigateBackAsync` works fine, the navigation occurs.

However, `NavigatorExtensions.NavigateBackWithResultAsync` doesn't navigate back but the result is processed and applied.

## Expected behavior

`NavigatorExtensions.NavigateBackWithResultAsync` should navigate back too.

## How to reproduce it (as minimally and precisely as possible)

This occurs in the Chef's App for flyouts where we use `NavigateBackWithResultAsync`, like on the UpdateCookbook page and Search page.

### UpdateCookbookPage
1. Open Chef's App & login
2. Click on "View all" at the top right
3. Click on the profile icon at the top right
4. Click on the cookbooks tab
5. Click on a "+" within one of the cookbook displays, to open the UpdateCookbook page
6. Add a recipe to the cookbook and click on "Done"
7. Notice that the flyout doesn't close (doesn't navigate back) and that the recipe was added to the cookbook

### SearchPage
1. Open Chef's App & login
2. Click on "View all" at the top right (or on the search icon)
3. Click on the filters button to open the filters flyout
4. Click on "Apply filters"
5. Notice that the flyout doesn't close and that the filters were applied to the search 
_(note: there's a display/functionality issue with the filters which currently causes them to behave a little weird, you can add a breakpoint to the filters and notice that they are indeed changed when you press on the "Apply filters" button)_ [here's the related issue](https://github.com/unoplatform/uno/issues/12820)

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [x] Windows
- [ ] Build tasks

Visual Studio:

- [x] 2022
- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by nickrandolph** [comment]
@rajamatt I'm closing this issue but post back here if this is still an issue
