### ISSUE TITLE
[Documentation]Mention package reference changes in v5 migration guide

### ISSUE THREAD

**Issue by lukeblevins** [unoplatform/uno.extensions#1664]
@lukeblevins can we add to v5 migration documentation:
- Remove Uno.Extensions.Toolkit and Uno.Extensions.Toolkit.UI/WinUI package references (no longer required)
- Remove Uno.Extensions package reference (no longer required)

_Originally posted by @nickrandolph in https://github.com/unoplatform/uno.extensions/issues/1640#issuecomment-1630391893_

**Comment by nickrandolph** [comment]
@agneszitte has the latest changes to docs resolved this?

**Comment by agneszitte** [comment]
> @agneszitte has the latest changes to docs resolved this?

@nickrandolph we will need to double-check everywhere as I can see this for example:
https://github.com/search?q=org%3Aunoplatform+Uno.Extensions.Toolkit+path%3A*.md&type=code

**Comment by agneszitte** [comment]
@eriklimakc as you will be helping for the extensions documentation, if you can help verifying what is left for this issue please
Thanks in advance
