### ISSUE TITLE
[Auth] No runtime pack for WindowsForms available 

### ISSUE THREAD

**Issue by morning4coffe-dev** [unoplatform/uno.extensions#1673]
## Current behavior
After adding the latest `Uno.Extensions.Authentication.MSAL.WinUI` to a new Default project I get this error:
`NETSDK1082	There was no runtime pack for Microsoft.WindowsDesktop.App.WindowsForms available for the specified RuntimeIdentifier 'win10-arm'.`

## How to reproduce it (as minimally and precisely as possible)
1. Create a new Uno project
2. Follow the docs for adding the package

## Environment

Nuget Package:
`Uno.Extensions.Authentication.MSAL.WinUI 2.4.2` 
or 
`Uno.Extensions.Authentication.MSAL.WinUI 3.0.0-dev.1984`

**Comment by nickrandolph** [comment]
Do you see this if you pick the MSAL option when creating a new app with the Wizard?

**Comment by nickrandolph** [comment]
Try updating the Microsoft.Identity.Client package (implicitly referenced by the msal package) to the latest stable release

**Comment by morning4coffe-dev** [comment]
It seems to have done the trick. Thanks!

**Comment by nickrandolph** [comment]
Ok, I think we'll update the uno.extensions.authentication.msal library to reference latest version of the client package
