### ISSUE TITLE
[Navigation][Documentation] Write advanced topic with `IRouteNotifier`, `NavigationResponse`, `INavigator`

### ISSUE THREAD

**Issue by lukeblevins** [unoplatform/uno.extensions#1679]
> @lukeblevins can we create an advanced topic that looks at using the IRouteNotifier and the NavigationResponse to access the INavigator. An example where this would be useful is opening a dialog where you might want to cancel the dialog via the INavigator instance

_Originally posted by @nickrandolph in https://github.com/unoplatform/uno.extensions/issues/1678#issuecomment-1645238935_

**Comment by eriklimakc** [comment]
We could use this PR https://github.com/unoplatform/uno.extensions/pull/2320 to add info regarding `NavigationResponse`, specifically to the [Navigator docs](https://github.com/unoplatform/uno.extensions/blob/main/doc/Reference/Navigation/Navigator.md?plain=1).
