### ISSUE TITLE
Write a proper repository description

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno.extensions#1802]
## What would you like to be added:

This repo is using the default description:

<img width="274" alt="image" src="https://github.com/unoplatform/uno.extensions/assets/1075116/4d36a7fb-52fa-49b5-b86d-026330e311ec">

## For which Platform:

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

**Comment by jeromelaban** [comment]
Changed it to: _Libraries to ease common developer tasks associated with building multi-platform mobile, desktop and web applications using Uno Platform or WinAppSDK_
