### ISSUE TITLE
Application crashes with COMException when creating CollectionViewSource property in Viewmodel

### ISSUE THREAD

**Issue by ttustonic** [unoplatform/uno.extensions#1837]
## Current behavior

Adding a public CollectionViewSource property in any ViewModel crashes application with the COMException
```
System.Runtime.InteropServices.COMException
  HResult=0x8001010E
  Message=The application called an interface that was marshalled for a different thread. (0x8001010E (RPC_E_WRONG_THREAD))
  ... etc ...

  at Uno.Extensions.Navigation.Navigators.ControlNavigator.<>c__DisplayClass8_0.<<CreateViewModel>b__0>d.MoveNext()
```

## Expected behavior

Application should not crash

## How to reproduce it (as minimally and precisely as possible)

Create Uno app from the Visual studio template.
Add
```
    public CollectionViewSource CollectionViewSource   {  get; private set;    } = new CollectionViewSource();
```
to the MainViewModel.
Start the application. 
It crashes 
## Environment

Nuget Package:
Uno.WinUI Version="4.9.45" 
Uno.Resizetizer Version="1.1.2" 
CommunityToolkit.Mvvm Version="8.2.0" 
Uno.Extensions.Logging.WinUI Version="2.4.2" 
Uno.Extensions.Hosting.WinUI Version="2.4.2" 
Uno.Extensions.Navigation.WinUI Version="2.4.2" 
Microsoft.Extensions.Logging.Console Version="7.0.0" 
Microsoft.WindowsAppSDK Version="1.3.230502000" 
Microsoft.Windows.SDK.BuildTools Version="10.0.22621.756" 

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders fo
- [x ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

[UnoApp2.zip](https://github.com/unoplatform/uno.extensions/files/12480864/UnoApp2.zip)

**Comment by ttustonic** [comment]
Workaround is to put CollectionViewSource creation in a IDispatcher:

 ```
public MainViewModel(INavigator navigator, IDispatcher dispatcher)
    {
        dispatcher.ExecuteAsync(() => CollectionViewSource = new());
       ... etc...
```

**Comment by nickrandolph** [comment]
Yes, this is by design - ViewModels are created on a background thread. For something like CollectionViewSource that is UI dependent, you'll need to create on UI thread via the dispatcher
