### ISSUE TITLE
[iOS] AppBar styles are not applied

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno.extensions#185]
## Current behavior

The iOS App from a template does not have styles applied properly.

## Expected behavior

The iOS App looks like the other platforms.

## How to reproduce it (as minimally and precisely as possible)

1. `dotnet new unoapp-extensions --material`
2. Build and run the `.iOS` head.

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [x] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by Xiaoy312** [comment]
possibly fixed by?: #188

**Comment by nickrandolph** [comment]
@jeromelaban / @Xiaoy312 I think this has been fixed as I'm seeing Material styles across both UI and WinUI versions of the ios sample app

**Comment by jeromelaban** [comment]
Yes, it's been fixed!
