### ISSUE TITLE
Request to Make WebAuthenticatorBrowser Class Public 

### ISSUE THREAD

**Issue by dim-37** [unoplatform/uno.extensions#1887]
## What would you like to be added:
Is it possible to make the WebAuthenticatorBrowser class from Uno.Extensions.Authentication.Oidc public?
## Why is this needed:
 I encountered an issue in my project where I couldn't utilize the available authorization tools from Uno.Extensions for all the providers I required, primarily because they lacked the authorization flow I needed. I aimed to utilize some internal implementation for specific parts of the code, which required direct interaction with the browser and waiting for the necessary redirection. During my investigation of the authorization implementation, I came across the WebAuthenticatorBrowser class. Why is it marked as internal? I believe it would be greatly beneficial if certain authorization components, were made public instead of being kept internal.
## For which Platform:

- [X] iOS
- [X] Android
- [X] WebAssembly
- [X] WebAssembly renders for Xamarin.Forms
- [X] Windows
- [ ] Build tasks

**Comment by xperiandri** [comment]
@nickrandolph will you allow making it public? So that we send a PR

**Comment by nickrandolph** [comment]
No reason we couldn't make it public. Wanted to avoid exposing something where API might change but if you need it, submit the PR

**Comment by nickrandolph** [comment]
I'm reviewing the PR you've provided and wondering what it is about this WebAuthenticatorBrowser class that you're particulary interested in being able to reuse. If you can provide more context here, we should be able to find a better solution than simply making the WebAuthenticatorBrowser public (this is really an internal class to support the OIDC auth workflow).

**Comment by dim-37** [comment]
I needed this functionality to provide Firebase-based authentication in my application. Due to the limitations of some providers not supporting authorization code flow, I had to directly implement authorization in Firebase, rather than simply registering OIDC providers and exchanging access tokens in Firebase. It might be better to encapsulate this process in a helper function or home kind of extension method.

**Comment by dim-37** [comment]
Here is an example of how I use it in a project 
```C#
private OidcAuthenticationProvider.WebAuthenticatorBrowser browser;
private FirebaseAuthClient firebaseAuthClient;
private string redirectUri;

public FirebaseService(FirebaseAuthConfig firebaseAuthConfig, string redirectUri)
{
    browser = new OidcAuthenticationProvider.WebAuthenticatorBrowser();
    firebaseAuthClient = new FirebaseAuthClient(firebaseAuthConfig);
    this.redirectUri = redirectUri;
}

private async Task<string> Redirect(string url)
{
    var options = new BrowserOptions(url, redirectUri);
    var result = await browser.InvokeAsync(options, CancellationToken.None);
    return result.Response;
}

public async Task<UserCredential> SignInWithFirebase(FirebaseProviderType provider)
    => await firebaseAuthClient.SignInWithRedirectAsync(provider, Redirect);
```

**Comment by nickrandolph** [comment]
ok, so we technically need to move the WbeAuthenticatorBrowser out.
Out of interest, why didn't you just use the WebAuthenticationProvider?

**Comment by xperiandri** [comment]
Because unofficial Firebase Auth SDK uses its own HTTP request logic but leaves browser handling logic to the user. And the Uno extensions provide this logic. So that we combine them
