### ISSUE TITLE
[Navigation] Slow Modal Page Navigation and GTK Logging

### ISSUE THREAD

**Issue by eriklimakc** [unoplatform/uno.extensions#1906]
## Current behavior

After changing navigation to Modal noticed a strange behavior, specially in GTK, but Android and Windows seem slower.

In Skia.GTK log messages keep poping up while the page is opened as in the image below:

![MicrosoftTeams-image (9)](https://github.com/unoplatform/uno.extensions/assets/114886335/ac0524c1-cd43-41dc-ad4e-566d941fef45)

Sometimes it crahses

![MicrosoftTeams-image (10)](https://github.com/unoplatform/uno.extensions/assets/114886335/2448afb6-eaed-4225-9eff-db42d3e7da18)

## How to reproduce it (as minimally and precisely as possible)

![image](https://github.com/unoplatform/uno.extensions/assets/114886335/4cc2fe8c-e2bb-4da7-8337-8259beeda016)

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
@eriklimakc could you revalidate this issue using the new desktop target?

**Comment by eriklimakc** [comment]
I wasn't able to reproduce the issue in the new desktop target. I didn't notice any slowness or continuous logs on the console.

@jeromelaban @kazo0
