### ISSUE TITLE
[Android][Commerce App] NavigationBar AppBarButton Icons are really small

### ISSUE THREAD

**Issue by agneszitte-nventive** [unoplatform/uno.extensions#192]
**IMPORTANT: Please double-check the other platforms while working on this issue and also both UWP/WinUI folders**

## Current behavior

NavigationBar AppBarButton Icons are really small on Android
![image](https://user-images.githubusercontent.com/16295702/144478476-721768f6-ed32-46c3-92d0-26fa7061bc8f.png)

## Expected behavior

NavigationBar AppBarButton Icons should be the same size on all platforms
![image](https://user-images.githubusercontent.com/16295702/144478534-caf757c1-3079-401d-8c59-d511fa1a9b0a.png)

## How to reproduce it (as minimally and precisely as possible)

- Launch the Commerce App Sample
- Login
- Notice the NavigationBar AppBarButton Icons on ProductPage

## Environment

Nuget Package: Uno.Toolkit.UI

Package Version(s): 1.0.0

Affected platform(s):
- [ ] iOS
- [X] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

**Comment by kazo0** [comment]
Looks to be some sort of issue with the dpi scaling on Android. on a MDPI device the icons are the proper size. On devices with higher HDPI will have tiny icons

![image](https://user-images.githubusercontent.com/4793020/145283037-073bf0a6-19fc-4e50-bdfb-55d1b40c62b5.png)

![image](https://user-images.githubusercontent.com/4793020/145283061-f63e6a06-24ae-42e0-a3fd-cbd270d85302.png)
