### ISSUE TITLE
[All Platforms][Commerce App] Blank line of 1px visible on top of everything in the App

### ISSUE THREAD

**Issue by agneszitte-nventive** [unoplatform/uno.extensions#194]
**IMPORTANT: Please double-check all the platforms while working on this issue and also both UWP/WinUI folders**

## Current behavior

Blank line of 1px visible on top of everything in the App

![image](https://user-images.githubusercontent.com/16295702/144480690-95ae30da-faec-4c3e-91a6-ab5abfedf9f8.png)

## Expected behavior

No blank line is visible

## How to reproduce it (as minimally and precisely as possible)

- Launch the Commerce App Sample
- Login
- Notice the blank line of 1px visible on top of everything in the App

## Environment

Nuget Package: Uno.Toolkit.UI

Package Version(s): 1.0.0

Affected platform(s):
- [X] iOS
- [X] MacOS
- [X] Skia
- [X] Android
- [X] WebAssembly
- [X] Windows

**Comment by nickrandolph** [comment]
@agneszitte-nventive I've checked this on Android, iOS, WinUI and UWP and it would appear this issue has been fixed. I'm not sure who worked on this though as there's no link to this issue

**Comment by jeromelaban** [comment]
Thanks Nick!
