### ISSUE TITLE
[iOS] [Commerce App] Cart page bottom is not supposed to have a gap at the end

### ISSUE THREAD

**Issue by agneszitte-nventive** [unoplatform/uno.extensions#196]
## Current behavior

Cart page bottom is not supposed to have a gap at the end that we can use to light dismiss 
![image](https://user-images.githubusercontent.com/16295702/144483022-6cb59d1f-3e8e-4d5f-8981-3427ae23c057.png)

## Expected behavior

Cart page should fill the entire screen and in order to go back you will use the close button at the top
![image](https://user-images.githubusercontent.com/16295702/144483155-c9f531cc-ae66-4a89-8fe2-8eec06fb0f7e.png)

## How to reproduce it (as minimally and precisely as possible)

- Launch the Commerce App Sample
- Login
- Navigate to the Cart tab
- Notice the bottom of the Cartpage

## Environment

Nuget Package: Uno.Toolkit.UI

Package Version(s): 1.0.0

Affected platform(s):
- [X] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

**Comment by Xiaoy312** [comment]
before i forget, the fix to make this fullscreen can be found here: https://github.com/unoplatform/uno/commit/2f15a02a29749a45c5a0e89e1476e50ed44dea15#diff-89b947d57a5648cf8a920a715b467a58d993da6e767fdcd08ceecfecb6a5ad9cR196-R212

todo: 
- [ ] need to go through existing styles to apply visibleboundspadding
- [ ] ensure they are light-dismissible when visibleboundspadding is present and applied
- [ ] sanity-check this doesnt break commerce/gallery/toolkit

**Comment by nickrandolph** [comment]
@Xiaoy312 I'm still seeing this space at the bottom of the cart on iOS (both UI and WinUI targets).

**Comment by agneszitte-nventive** [comment]
We will be able to come back to this issue after your changes (https://github.com/unoplatform/uno.extensions/pull/228) are merged @nickrandolph in order to better assess what will be the plan.
(cc @jeromelaban, @kazo0 and @Xiaoy312)

**Comment by nickrandolph** [comment]
@agneszitte-nventive #228 has been merged and I've confirmed this issue is still present on iOS. 
@Xiaoy312 the change to uno that you linked to, has that been released in a new stable build of Uno? Are there additional changes we need to make to styles to fix this issue on iOS
