### ISSUE TITLE
[Commerce App] ToggleSwitch not aligned in Profile page

### ISSUE THREAD

**Issue by agneszitte-nventive** [unoplatform/uno.extensions#198]
**IMPORTANT: Please double-check the other platforms while working on this issue and also both UWP/WinUI folders**

## Current behavior

ToggleSwitch not aligned in Profile page
![image](https://user-images.githubusercontent.com/16295702/144485042-e53ff14a-3716-470a-91b0-7363f90b1de2.png)

## Expected behavior

ToggleSwitch is aligned in Profile page

## How to reproduce it (as minimally and precisely as possible)

- Launch the Commerce App Sample
- Login
- Navigate to the profile tab
- Notice the ToggleSwitch button

## Environment

Nuget Package: Uno.Toolkit.UI

Package Version(s): 1.0.0

Affected platform(s):
- [X] iOS
- [X] macOS
- [X] Android
- [X] WebAssembly
- [X] Skia
- [ ] Windows
- [ ] Build tasks

**Comment by carldebilly** [comment]
https://github.com/microsoft/microsoft-ui-xaml/issues/6157

**Comment by nickrandolph** [comment]
@agneszitte-nventive I've checked this on various platforms and it would appear that the fix applied by @Xiaoy312 is working. Can you confirm this has addressed this issue

**Comment by jeromelaban** [comment]
Let's close this for now then.
