### ISSUE TITLE
`Uno.Extensions.Toolkit` packages should be marked as deprecated on NuGet

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno.extensions#2002]
## Current behavior

The `Uno.Extensions.Toolkit` packages are not marked deprecated, and the seem to be updated normally. Only after install the user is notified.

## Expected behavior

Should be clearly marked as deprecated on NuGet.

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by nickrandolph** [comment]
cc @jeromelaban are you able to mark these as deprecated in nuget?

**Comment by jeromelaban** [comment]
Done, it's marked as deprecated in nuget.
