### ISSUE TITLE
[Skia][Commerce App] NavigationView menu icon doesn't display correctly

### ISSUE THREAD

**Issue by agneszitte-nventive** [unoplatform/uno.extensions#203]
**IMPORTANT: Please double-check the other platforms while working on this issue and also both UWP/WinUI folders**

## Current behavior

NavigationView menu icon doesn't display correctly on Skia
![image](https://user-images.githubusercontent.com/16295702/144490710-d90c4cbb-cea5-4c1e-bd87-70d5d6cbdd81.png)

## Expected behavior

NavigationView menu icon should display correctly on all platforms
![image](https://user-images.githubusercontent.com/16295702/144490839-d517c553-6d6c-4286-a8df-91abf1233d17.png)

## How to reproduce it (as minimally and precisely as possible)

- Launch the Commerce App Sample
- Login
- Notice the NavigationView menu icon on the top left

## Environment

Nuget Package: Uno.Toolkit.UI

Package Version(s): 1.0.0

Affected platform(s):
- [ ] iOS
- [ ] macOS
- [ ] Android
- [ ] WebAssembly
- [x] Skia
- [ ] Windows
- [ ] Build tasks

**Comment by MartinZikmund** [comment]
![image](https://user-images.githubusercontent.com/1075116/156932830-f3c6438d-137a-4835-bd79-4bed96a2a543.png)

Seems this is working now
