### ISSUE TITLE
[Navigation] [iOS] Unable to interact with control after navigating back

### ISSUE THREAD

**Issue by mcocaroUX** [unoplatform/uno.extensions#2113]
## Current behavior

Rating control won't work after navigation to next page and then going back. The control just doesn't react to the interactions

## Expected behavior

Control should update when interacting after navigating back

## How to reproduce it (as minimally and precisely as possible)

1- Run app
2- See how rating control works correctly
3- Go to second page and then back to main page
4 - Notice how you are unable to interact with the RatingControl

[UnoApp.zip](https://github.com/unoplatform/uno.extensions/files/13709425/UnoApp.zip)

## Environment

Nuget Package(s):

Package Version(s):

Affected platform(s):

- [X] iOS
- [ ] macOS (AppKit)
- [ ] Mac Catalyst
- [ ] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Skia (WPF)
- [ ] Skia (GTK on Linux/macOS/Windows)
- [ ] Skia (Linux Framebuffer)
- [ ] Build tasks

Visual Studio:

- [ ] 2019 (version: )
- [X] 2022 (version: )
- [ ] #2124
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by johnkattenhorn** [comment]
Hey @MartinZikmund - thanks so much for fixing this - do you know when this is likely to ship as we have a client waiting for it ? would it be easy enough for the engineer to bring this in a source into a project temporary until next release cycle. FAO (@mcocaroUX)
