### ISSUE TITLE
[MacCatalyst] [Authentication][Storage] Unknown error when authenticating

### ISSUE THREAD

**Issue by mcocaroUX** [unoplatform/uno.extensions#2126]
## Current behavior

When using custom authentication on Mac, after login gets executed it thows an exception at Uno.Extensions.Storage.UI. This behavior is present also when you create a blank app with the Custom auth option selected.

## Expected behavior

Authentication should work as does on other platforms

## How to reproduce it (as minimally and precisely as possible)

1- Run project on Mac
2- Try to login
[ReproProject.zip](https://github.com/unoplatform/uno.extensions/files/13795971/ReproProject.zip)

## Environment

Nuget Package (s):

```
<PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="7.0.0" />
<PackageVersion Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.22621.756" />
<PackageVersion Include="Microsoft.WindowsAppSDK" Version="1.4.231008000" />
<PackageVersion Include="Uno.Core.Extensions.Logging.Singleton" Version="4.0.1" />
<PackageVersion Include="Uno.Extensions.Authentication" Version="3.0.19" />
<PackageVersion Include="Uno.Extensions.Authentication.WinUI" Version="3.0.19" />
<PackageVersion Include="Uno.Extensions.Configuration" Version="3.0.19" />
<PackageVersion Include="Uno.Extensions.Hosting" Version="3.0.19" />
<PackageVersion Include="Uno.Extensions.Hosting.WinUI" Version="3.0.19" />
<PackageVersion Include="Uno.Extensions.Http" Version="3.0.19" />
<PackageVersion Include="Uno.Extensions.Http.WinUI" Version="3.0.19" />
<PackageVersion Include="Uno.Extensions.Http.Refit" Version="3.0.19" />
<PackageVersion Include="Uno.Extensions.Localization" Version="3.0.19" />
<PackageVersion Include="Uno.Extensions.Localization.WinUI" Version="3.0.19" />
<PackageVersion Include="Uno.Extensions.Logging.OSLog" Version="1.7.0" />
<PackageVersion Include="Uno.Extensions.Logging.WinUI" Version="3.0.19" />
<PackageVersion Include="Uno.Extensions.Navigation" Version="3.0.19" />
<PackageVersion Include="Uno.Extensions.Navigation.WinUI" Version="3.0.19" />
<PackageVersion Include="Uno.Extensions.Navigation.Toolkit.WinUI" Version="3.0.19" />
<PackageVersion Include="Uno.Extensions.Reactive" Version="3.0.19" />
<PackageVersion Include="Uno.Extensions.Reactive.WinUI" Version="3.0.19" />
<PackageVersion Include="Uno.Extensions.Serialization" Version="3.0.19" />
<PackageVersion Include="Uno.Extensions.Serialization.Http" Version="3.0.19" />
<PackageVersion Include="Uno.Extensions.Serialization.Refit" Version="3.0.19" />
<PackageVersion Include="Uno.Material.WinUI" Version="4.0.6" />
<PackageVersion Include="Uno.Toolkit.WinUI" Version="5.0.19" />
<PackageVersion Include="Uno.Toolkit.WinUI.Material" Version="5.0.19" />
<PackageVersion Include="Uno.Resizetizer" Version="1.2.1" />
<PackageVersion Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="5.0.118" />
<PackageVersion Include="Uno.UniversalImageLoader" Version="1.9.36" />
<PackageVersion Include="Uno.WinUI" Version="5.0.118" />
<PackageVersion Include="Uno.WinUI.Lottie" Version="5.0.118" />
<PackageVersion Include="Uno.WinUI.DevServer" Version="5.0.118" />
```

Affected platform(s):

- [ ] iOS
- [ ] macOS (AppKit)
- [X] Mac Catalyst
- [ ] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Skia (WPF)
- [ ] Skia (GTK on Linux/macOS/Windows)
- [ ] Skia (Linux Framebuffer)
- [ ] Build tasks

Visual Studio:

- [ ] 2019 (version: )
- [ ] 2022 (version: )
- [X] Visual Studio Code (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

![image](https://github.com/unoplatform/uno.extensions/assets/94198647/01030791-c327-4efa-b285-81b8ab4b9cd3)

**Comment by nickrandolph** [comment]
@mcocaroUX can you try adding the following entitlement to the Entitlements.plist file

https://github.com/unoplatform/uno.extensions/blob/f14f671185720aa1663f65ce5e7805bdfbd29ff4/testing/TestHarness/TestHarness.Mobile/iOS/Entitlements.plist#L5-L8

**Comment by spouliot** [comment]
The error hints to a missing entitlements.

```
0xFFFF7B1E	-34018	A required entitlement isn't present.
```
ref: https://georgegarside.com/blog/macos/macos-security-error-codes/

But adding the proposed XML just makes the app hangs at startup.

There's a new warning when adding the proposed XML  into the `Entitlements.plist`.

```
MacCatalyst/Entitlements.plist : warning : Cannot expand $(AppIdentifierPrefix) in Entitlements.plist without a provisioning profile. [/Users/poupou/Downloads/ReproProject/ReproProject/ReproProject.Mobile/ReproProject.Mobile.csproj]
```

But even when fixed, by removing `$(AppIdentifierPrefix)`, the situation remains identical.

Adding the same entitlement to a new dotnet (non MAUI) maccatalyst project also results in an app that hangs. IOW it's not related to Uno or using the Uno Platform extension for VS Code.

Looking at the logs (inside Console.app) we can see

```
mac_vnode_check_signature: /Users/poupou/Downloads/ReproProject/ReproProject/ReproProject.Mobile/bin/Debug/net7.0-maccatalyst/maccatalyst-arm64/ReproProject.Mobile.app/Contents/MacOS/ReproProject.Mobile: code signature validation failed fatally: When validating /Users/poupou/Downloads/ReproProject/ReproProject/ReproProject.Mobile/bin/Debug/net7.0-maccatalyst/maccatalyst-arm64/ReproProject.Mobile.app/Contents/MacOS/ReproProject.Mobile:
  Code has restricted entitlements, but the validation of its code signature failed.
Unsatisfied Entitlements:
```

which match the result of

```
pkgutil --check-signature ./bin/Debug/net8.0-maccatalyst/maccatalyst-arm64/maccatalyst.app
Package "maccatalyst":
   Status: invalid signature
```

It looks like something in the dotnet SDK is not doing the correct signing steps when the entitlements are included.

**Comment by spouliot** [comment]
Ok, this works fine. My problem were
1. that my apple developer membership needed to be renewed
2. the dotnet SDK does give much hints for such errors

The easiest way to fix such an issue is to use Xcode and create a new (catalyst) app with the same **bundle identifier** as your app.

Then under **Signing and Capabilities** you can add the **Keychain Sharing** capability (for your bundle identifier) and finally ask Xcode to update the `Xcode Managed Profile`.

Back to your app edit your `.csproj` to include the same information as Xcode. E.g.

```xml
<PropertyGroup>
  <CodesignEntitlements>MacCatalyst\Entitlements.plist</CodesignEntitlements>
  <CodesignKey>Apple Development: Sebastien Pouliot (XXXXXXXXXX)</CodesignKey>
  <CodesignProvision>Mac Catalyst Team Provisioning Profile: com.companyname.maccatalyst</CodesignProvision>
</PropertyGroup>
```

Next re-build the app and you won't get the security error/exception you had from Uno.Extensions.Storage.UI.

**Comment by francoistanguay** [comment]
Am not following. How much of this can be automaed/provided guidance for/supported right out of our templates?

**Comment by spouliot** [comment]
Sadly, it cannot really be automated 😢 

What needs to happen must be done inside [Apple Developer Portal](https://developer.apple.com/help/account/get-started/sign-in-to-your-developer-account/) (or, for simpler cases, inside Xcode). Apple does not provide tools/API to automate the [various actions](https://developer.apple.com/help/account/) that can be made from the portal.

On Catalyst (and likely iOS too) the Uno.Extensions.Storage.UI code use some KeyChain APIs. Those API will only work if the 
**Keychain Sharing** is [enabled](https://developer.apple.com/documentation/security/keychain_services/keychain_items/sharing_access_to_keychain_items_among_a_collection_of_apps/) _and_ it must specify the application bundle id (which is different for each application).

On top of that the addition of entitlements (like **Keychain Sharing**) requires the application to be signed (which is something you can avoid for most simple apps). So you need to set this up (if you have not already done so).

Like the application bundle id, the identity and provisioning profile names are not constants (across projects or users).

This is why this ends up with a custom property group inside the `.csproj`.

As for providing guidance I guess this should be part of the documentation (from a quick glance it does not look like it's present).

Also I guess we could catch the exception and print some logs that points back to this documentation. That would avoid searching thru a lot of web pages mentioning the same error code.

**Comment by francoistanguay** [comment]
So can we have clear docs for this and link them from the Auth docs or wherever it makes sense?
