### ISSUE TITLE
[Navigation] Uno.Extensions.Navigation.UI..Region Logger not set prior to navigating in MVUX project.

### ISSUE THREAD

**Issue by MarkAllan007** [unoplatform/uno.extensions#2159]
### Current behavior

Use Uno Wizard to setup a MVUX project which allows us to use NavigationView paired with Regions.
With minimum modifications, update the shells.xaml.cs xaml to include the markup below.
Leave most of the app.cs file the same. I removed the secondpage from the project.

A. shell.xaml file should contain two groups of markup. One group is commented out, the other is not. Uncomment and run the "NavigationView" markup. The execution reports an error: ...  Region Logger is null.

B. Comment out the "NavigationView" markup and uncomment the "extended splash screen" markup. Run the "extended splash screen" markup. The Region Logger is set to a valid logger.

### Expected behavior

The expected behavior for both sets of markup is that the Region Logger is properly set to a valid logger and will not throw and exception.

### How to reproduce it (as minimally and precisely as possible)

Use Uno Wizard to setup a MVUX project which allows us to use NavigationView paired with Regions.
With minimum modifications, update the shells.xaml.cs xaml to include the markup below.
Leave most of the app.cs file the same. I removed the secondpage from the project.

A. shell.xaml file should contain two groups of markup. One group is commented out, the other is not. Uncomment and run the "NavigationView" markup. The execution reports an error: ...  Region Logger is null.

B. Comment out the "NavigationView" markup and uncomment the "extended splash screen" markup. Run the "extended splash screen" markup. The Region Logger is set to a valid logger.

Sample markup to test with.

<UserControl x:Class="UnoExtenApp005.Presentation.Shell"
      xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
      xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
      xmlns:local="using:UnoExtenApp005.Presentation"
      xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
      xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
      xmlns:muxc="using:Microsoft.UI.Xaml.Controls"  
      xmlns:uen="using:Uno.Extensions.Navigation.UI"
      xmlns:utu="using:Uno.Toolkit.UI"
      xmlns:um="using:Uno.Material"             
      mc:Ignorable="d"
      d:DesignHeight="300"
      d:DesignWidth="400">

  
  
  
  

  <Grid uen:Region.Attached="True" uen:Region.Navigator="Visibility">
    <Grid.RowDefinitions>
      <RowDefinition Height="Auto" />
      <RowDefinition />
    </Grid.RowDefinitions>

    <utu:NavigationBar Content="Main Page"  />

    <muxc:NavigationView Grid.Row="1" x:Name="NavView" uen:Region.Attached="True">
      <muxc:NavigationView.MenuItems>
        <muxc:NavigationViewItem Content="Main" uen:Region.Name="Main" />
      </muxc:NavigationView.MenuItems>

      <muxc:NavigationView.Content>
        <Grid>
          <Grid.RowDefinitions>
            <RowDefinition />
            <RowDefinition Height="Auto" />
          </Grid.RowDefinitions>

          <Grid uen:Region.Attached="True">
            <Grid Visibility="Collapsed" uen:Region.Name="Main">
              <TextBlock Text="Main"
                                  FontSize="24"
                                  HorizontalAlignment="Center"
                                  VerticalAlignment="Center" />
            </Grid>

          </Grid>
        </Grid>
  
      </muxc:NavigationView.Content>
    </muxc:NavigationView>

  </Grid>

  

</UserControl>  

### Workaround

I don't know of a work around.

### Works on UWP/WinUI

None

### NuGet package version(s)

<Project ToolsVersion="15.0">
  <ItemGroup>
    <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="8.0.0" />
    <PackageVersion Include="coverlet.collector" Version="6.0.0" />
    <PackageVersion Include="FluentAssertions" Version="6.12.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageVersion Include="NUnit" Version="4.0.1" />
    <PackageVersion Include="NUnit3TestAdapter" Version="4.5.0" />
    <PackageVersion Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageVersion Include="Microsoft.Windows.Compatibility" Version="8.0.0" />
    <PackageVersion Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.22621.2428" />
    <PackageVersion Include="Microsoft.WindowsAppSDK" Version="1.4.231219000" />
    <PackageVersion Include="Serilog.AspNetCore" Version="8.0.1" />
    <PackageVersion Include="SkiaSharp.Skottie" Version="2.88.7" />
    <PackageVersion Include="SkiaSharp.Views.Uno.WinUI" Version="2.88.7" />
    <PackageVersion Include="Swashbuckle.AspNetCore" Version="6.5.0" />
    <PackageVersion Include="Uno.Core.Extensions.Logging.Singleton" Version="4.0.1" />
    <PackageVersion Include="Uno.Extensions.Core.WinUI" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Configuration" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Hosting" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Hosting.WinUI" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Http" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Http.WinUI" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Http.Refit" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Localization" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Localization.WinUI" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Logging.WebAssembly.Console" Version="1.7.0" />
    <PackageVersion Include="Uno.Extensions.Logging.Serilog" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Logging.WinUI" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Navigation" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Navigation.WinUI" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Navigation.Toolkit.WinUI" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Reactive" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Reactive.WinUI" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Serialization" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Serialization.Http" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Serialization.Refit" Version="4.0.0" />
    <PackageVersion Include="Uno.Material.WinUI" Version="4.1.0" />
    <PackageVersion Include="Uno.Dsp.Tasks" Version="1.2.8" />
    <PackageVersion Include="Uno.Toolkit.WinUI" Version="5.1.3" />
    <PackageVersion Include="Uno.Toolkit.WinUI.Material" Version="5.1.3" />
    <PackageVersion Include="Uno.Resizetizer" Version="1.2.1" />
    <PackageVersion Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="$(UnoVersion)" />
    <PackageVersion Include="Uno.UniversalImageLoader" Version="1.9.36" />
    <PackageVersion Include="Uno.Wasm.Bootstrap" Version="9.0.0-dev.27" />
    <PackageVersion Include="Uno.Wasm.Bootstrap.DevServer" Version="9.0.0-dev.27" />
    <PackageVersion Include="Uno.Wasm.Bootstrap.Server" Version="9.0.0-dev.27" />
    <PackageVersion Include="Uno.WinUI" Version="$(UnoVersion)" />
    <PackageVersion Include="Uno.WinUI.Lottie" Version="$(UnoVersion)" />
    <PackageVersion Include="Uno.WinUI.DevServer" Version="$(UnoVersion)" />
    <PackageVersion Include="Uno.WinUI.Skia.Gtk" Version="$(UnoVersion)" />
    <PackageVersion Include="Uno.WinUI.WebAssembly" Version="$(UnoVersion)" />
    <PackageVersion Include="Uno.UITest.Helpers" Version="1.1.0-dev.70" />
    <PackageVersion Include="Xamarin.UITest" Version="4.3.3" />
  </ItemGroup>
</Project>

### IDE

Visual Studio 2022

### IDE version

17.8.5

### Relevant plugins

Uno Platform 5.1.22.24

### Anything else we need to know?

I walking through your examples.  I start with using your wizard to create projects. I am testing some of Uno features the systems use of MVUX for navigation. But wanted to see how to use it with the NavigationView tools. I'm looking to see the extent use cases that allow for freestyle navigation.

Thanks so much,
Mark Allan

**Comment by MarkAllan007** [comment]
![Shell xaml for testing uno platform app startup 001](https://github.com/unoplatform/uno.extensions/assets/4197055/6f099d6c-acbb-4c86-af5e-575830542250)

**Comment by MarkAllan007** [comment]
After doing some regression testing, my impression is this attribute  [ uen:Region.Attached="True" ]  is rerouting the app hosting's initialization.  Either intentionally or by causing an exception?

**Comment by xperiandri** [comment]
I have similar issue but my error make no sense at all

```XAML
<UserControl x:Class="eCierge.Console.Presentation.Shell"
      xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
      xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
      xmlns:local="using:eCierge.Console.Presentation"
      xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
      xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
      xmlns:uen="using:Uno.Extensions.Navigation.UI"
      xmlns:utu="using:Uno.Toolkit.UI"
      mc:Ignorable="d"
      d:DesignHeight="300"
      d:DesignWidth="400">
  <Grid Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
    <Grid.RowDefinitions>
      <RowDefinition Height="Auto"/>
      <RowDefinition Height="*"/>
    </Grid.RowDefinitions>
    <utu:NavigationBar />
    <NavigationView x:Name="NavView"
                    Grid.Row="1"
                    uen:Region.Attached="True"
                    >
      <NavigationView.MenuItems>
        <NavigationViewItem Content="Main" uen:Region.Name="Main" />
        <NavigationViewItem Content="Second" uen:Region.Name="Second" />
      </NavigationView.MenuItems>

      <!--<Frame uen:Region.Attached="True"/>-->
    </NavigationView>
    <!--<utu:ExtendedSplashScreen x:Name="Splash"
                HorizontalAlignment="Stretch"
                VerticalAlignment="Stretch"
                HorizontalContentAlignment="Stretch"
                VerticalContentAlignment="Stretch">
    <utu:ExtendedSplashScreen.LoadingContentTemplate>
      <DataTemplate>
        <Grid>
          <Grid.RowDefinitions>
            <RowDefinition Height="2*" />
            <RowDefinition />
          </Grid.RowDefinitions>

          <ProgressRing IsActive="True"
                  Grid.Row="1"
                  VerticalAlignment="Center"
                  HorizontalAlignment="Center"
                  Height="100"
                  Width="100" />
        </Grid>
      </DataTemplate>
    </utu:ExtendedSplashScreen.LoadingContentTemplate>
  </utu:ExtendedSplashScreen>-->
  </Grid>
</UserControl>
```

My shell crashes, in any case, I have `uen:Region.Attached="True"` placed either on the `NavigationView` or the root `Grid`

![image](https://github.com/unoplatform/uno.extensions/assets/2365592/a9eb3547-2ec6-4c85-839f-0cd01a4d68c9)
![image](https://github.com/unoplatform/uno.extensions/assets/2365592/9dd0fcb8-ccc1-4b80-ad46-3eee83e30335)

**Comment by xperiandri** [comment]
So I've figured out what is the issue. The `ExtendedSplashScreen` added to the template not just for fun or demo purposes.
`Region` needs a logger
Logger is being set by hosted service
Hosted service starts with some delay
`ExtendedSplashScreen` reacts to event of all hosted services being started

Hence if you try to use `Region` in the `Shell` then logger is not set yet.

@nickrandolph it is very confusing! There is no mentions of such logic anywhere! I spent 1 day figuring out why this happens. Which required me to copy 2 projects from Uno.Extenstions to a sample solution from template with my code to figure out that.

And calling a splash screen as shell is very confusing too. Because the shell is where you put NavigationView and TabBar.
And if you cannot put NavigationView or TabBar into an `ExtendedSplashScreen` which is a part of shell it is no longer a shell.
cc @jeromelaban

**Comment by sasakrsmanovic** [comment]
@weitzhandler @lukeblevins FYI too as I know you did some documentation on this front.

**Comment by xperiandri** [comment]
@MarkAllan007 were you able to verify that my suggestion works?

**Comment by MarkAllan007** [comment]
@xperiandri  Sorry this error slowed you down. Glad you found a work around.

No, I have not been working on a solution for this. I did trace through this apps initialization, looking at differences in the markup, leading to the exception. 

I do not have a stake in using Regions, yet. I was/am curious about them.  I was looking .Net 8 & Uno's implementation of NavigationView/ViewItems. We can embed NavigationViewItems in user controls.

I was looking at Regions, because I came across this error: https://github.com/unoplatform/uno.extensions/issues/2163

In setting up my NavigtionViewItems, I found that my ShellViewModel's constructor was not being instantiated. Some slight changes in the shells xaml statement, can change something.

It looks like Regions maybe an better, easier tool to use, than using NavigatioViewItems paired with boil-plate code-behind. This would be nice to test this. 

I got stuck with issue 2163, then was stuck here. I wanted to let the team know. 

If I find some time, I will definitely look for a clean solution. :-)

**Comment by nickrandolph** [comment]
@xperiandri @MarkAllan007 apologies for the delay in getting to this - documentation on regions is in the works (hopefully this week) and I realise that the ShellView/ViewModel may be confusing. If you're using NavigationView/TabBar they should go on your MainPage, rather than the ShellView.
