### ISSUE TITLE
[Android][Commerce App] Fab TabBarItem is not displaying correctly the Material Style

### ISSUE THREAD

**Issue by agneszitte-nventive** [unoplatform/uno.extensions#216]
## Current behavior

 Fab TabBarItem is not displaying correctly the Material Style for Android

![image](https://user-images.githubusercontent.com/16295702/145428392-74b0fceb-40bc-4de3-bbd6-dc47eae29e13.png)

## Expected behavior

 Fab TabBarItem should display correctly while using the Material Style on all platforms

![image](https://user-images.githubusercontent.com/16295702/145427636-0e1f78ff-a694-4791-8973-2998f287b9ed.png)

## How to reproduce it (as minimally and precisely as possible)

- Launch Commerce app
- Login
- On main page notice the bottom TabBar

## Environment

Affected platform(s):

- [ ] iOS
- [X] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

**Comment by nickrandolph** [comment]
@agneszitte-nventive can you confirm this was fixed by the changes @kazo0 made. I've tested this on both Droid - UI and Droid - WinUI and it appears correct but would like someone else to confirm this before we close off this issue
