### ISSUE TITLE
[Hosting] Adjust Application Host builder create window

### ISSUE THREAD

**Issue by dansiegel** [unoplatform/uno.extensions#2190]
## What would you like to be added:

This should be updated as the proper way to do this in Uno has changed:
https://github.com/unoplatform/uno.extensions/blob/51c9c1ef14f686363f946588733faecc5a1863ff/src/Uno.Extensions.Hosting.UI/ApplicationBuilder.cs#L10-L14

We should instead just return `new Window()`

## Why is this needed:

Multi-Window

**Comment by nickrandolph** [comment]
Fixed by https://github.com/unoplatform/uno.extensions/pull/2246
