### ISSUE TITLE
File appsettings.json are not being read

### ISSUE THREAD

**Issue by eriklimakc** [unoplatform/uno.extensions#2224]
### Current behavior

appsettings.json config are not being read.

`Uno.Extensions.Storage.FileStorage: Warning: ReadPackageFileAsync - File 'appsettings.appconfig.json' does not exist in package`.

![image](https://github.com/unoplatform/uno-private/assets/114886335/37cbe873-742d-4fc6-a16c-9e9446880694)

Something similar happens with **[TubePlayer ](https://github.com/unoplatform/Uno.Samples/pull/640)** after updating to latest template where in `httpClient.BaseAddress = new Uri(options!.Url!);` `options!` is null, and that comes from appsettings.development.json. My theory is that that file is not being found.

![image](https://github.com/unoplatform/uno-private/assets/114886335/337ea025-f1a1-4663-b9b6-78db03aeffac)

### How to reproduce it (as minimally and precisely as possible)

1. Create an uno app using the latest Uno.Template and add the Configuration feature
2. Run the app
3. Check if appsettings.json config are being read

### Works on UWP/WinUI

None

### NuGet package version(s)

Uno.Templates::5.2.0-dev.217

`"Uno.Sdk": "5.2.0-dev.2279"`

```xml
<UnoExtensionsVersion>4.1.0-dev.74</UnoExtensionsVersion>
<UnoToolkitVersion>5.2.0-dev.48</UnoToolkitVersion>
<UnoThemesVersion>4.2.0-dev.26</UnoThemesVersion>
<UnoCSharpMarkupVersion>5.2.0-dev.61</UnoCSharpMarkupVersion>
```

### IDE

Visual Studio

**Comment by jeromelaban** [comment]
@eriklimakc can you specify which target you're running?

**Comment by eriklimakc** [comment]
I could repro this with @nickrandolph before. I faced this in all targets. I tested again today on Windows and WASM with the latest sdk. I wasn't able to launch Desktop and Android though, for some reason... But they probably have the same issue.

WASM:

![image](https://github.com/unoplatform/uno.extensions/assets/114886335/253249fc-7032-4d7c-a69c-031253ba4b71)


cc @jeromelaban

**Comment by jeromelaban** [comment]
@eriklimakc I'm not reproducing the issue with the latest template, could you try again?

**Comment by eriklimakc** [comment]
> @eriklimakc I'm not reproducing the issue with the latest template, could you try again?

@jeromelaban yes, I tried again with Uno.Templates 5.2.0-dev.232 and Uno.Sdk 5.2.0 and got the same issue. Apparently Nick has a fix for it :)

**Comment by eriklimakc** [comment]
I can still repro with:

```xml
<UnoExtensionsVersion>4.2.0-dev.6</UnoExtensionsVersion>
```

`"Uno.Sdk": "5.2.0-dev.2290"` and same for `"Uno.Sdk": "5.3.0-dev.63"` 

`Uno.Templates: 5.2.0-dev.254`

I created an app with: 

```ps1
dotnet new unoapp -o Commerce -preset "recommended" -id "com.companyname.Commerce" -pub "O=Commerce1" -theme-service  -theme "material" -presentation "mvux" -config  -di  -log "default" -nav "regions" -http  -loc  -server False -tests "none" -toolkit  -dsp
```

![image](https://github.com/unoplatform/uno.extensions/assets/114886335/2d523f98-5674-4a8e-8351-325f1301d07c)

[Commerce.zip](https://github.com/unoplatform/uno.extensions/files/14875376/Commerce.zip)

cc @nickrandolph @vatsashah45
