### ISSUE TITLE
Rectangle draws too big shape (in C# markup)

### ISSUE THREAD

**Issue by kucint** [unoplatform/uno.extensions#2232]
## Current behavior

Following code should draw a rectangle of size 10x6
```
new Rectangle()
    .Width(10)
    .Height(6)
    .StrokeThickness(1)
    .Stroke(Colors.Black)
```
but it draws a rectangle of size 13x8
(anti-aliased inner rectangle has size 11x6)

This is original screenshot:
![image](https://github.com/unoplatform/uno.extensions/assets/54866088/1f29254a-be9b-4312-931b-e7013a814cb2)

This is the same screenshot zoomed in Paint:

![image](https://github.com/unoplatform/uno.extensions/assets/54866088/87e4dcbd-a5bd-44fc-8e2f-43dca007e893)

## Expected behavior

The code should draw a rectangle of size 10x6

## How to reproduce it (as minimally and precisely as possible)

**STEPS TO REPRODUCE**
- create a new Uno project, select:
    - windows only
    - C# markup
    - MVUX
  - replace default MainPage content with provided snippet

**MINIMAL REPRO PROJECT**

## Environment

```
{
  "msbuild-sdks": {
    "Uno.Sdk": "5.1.104",
    "Microsoft.Build.NoTargets": "3.7.56"
  }
}
```
Nuget Package (s):

```
<Project ToolsVersion="15.0">
  <ItemGroup>
    <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="8.0.0" />
    <PackageVersion Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.22621.2428" />
    <PackageVersion Include="Microsoft.WindowsAppSDK" Version="1.4.231219000" />
    <PackageVersion Include="Uno.Core.Extensions.Logging.Singleton" Version="4.0.1" />
    <PackageVersion Include="Uno.Extensions.Core.WinUI" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Hosting" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Hosting.WinUI" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Logging.WinUI" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Reactive" Version="4.0.0" />
    <PackageVersion Include="Uno.Extensions.Reactive.WinUI" Version="4.0.0" />
    <PackageVersion Include="Uno.Toolkit.WinUI" Version="5.1.7" />
    <PackageVersion Include="Uno.Resizetizer" Version="1.4.0" />
    <PackageVersion Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="$(UnoVersion)" />
    <PackageVersion Include="Uno.UniversalImageLoader" Version="1.9.36" />
    <PackageVersion Include="Uno.WinUI" Version="$(UnoVersion)" />
    <PackageVersion Include="Uno.WinUI.Lottie" Version="$(UnoVersion)" />
    <PackageVersion Include="Uno.WinUI.Markup" Version="5.1.5" />
    <PackageVersion Include="Uno.Extensions.Markup.Generators" Version="5.1.5" />
    <PackageVersion Include="Uno.Toolkit.WinUI.Markup" Version="5.1.3" />
    <PackageVersion Include="Uno.Extensions.Reactive.WinUI.Markup" Version="4.0.0" />
    <PackageVersion Include="Uno.Themes.WinUI.Markup" Version="4.1.1" />
    <PackageVersion Include="Uno.WinUI.DevServer" Version="$(UnoVersion)" />
  </ItemGroup>
</Project>
```

Affected platform(s):

- [ ] iOS
- [ ] macOS (AppKit)
- [ ] Mac Catalyst
- [ ] Android
- [ ] WebAssembly
- [x] Windows
- [ ] Skia (WPF)
- [ ] Skia (GTK on Linux/macOS/Windows)
- [ ] Skia (Linux Framebuffer)
- [ ] Build tasks

Visual Studio:

- [ ] 2019 (version: )
- [x] 2022 (version: 17.9.5)
- [ ] Visual Studio Code (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?
checked only on windows. Other platforms - behavior unknown.

**Comment by Youssef1313** [comment]
Maybe there is DPI scaling?
