### ISSUE TITLE
[iOS] Back button is not working in app from template

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno.extensions#225]
## Current behavior

Tapping on the back button does not work:
![image](https://user-images.githubusercontent.com/5839577/145869034-13477d91-8ddd-4f2a-ad04-816324d760fc.png)

## Expected behavior

Back works properly.

## How to reproduce it (as minimally and precisely as possible)

Create an app from the unoapp-extensions template.

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [x] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by nickrandolph** [comment]
@jeromelaban what device was this running on?  The navigationview shouldn't be visible on a phone device (in portrait) and there should only be a back button when user has navigated to product details
I've checked the iOS UI and iOS WinUI sample apps and the appearance of the navigationview and back button appears to be working correctly

**Comment by jeromelaban** [comment]
This was on an iPad. The button appears because the screen is wide.

**Comment by kazo0** [comment]
Is this still happening, not able to get the back button to appear in iPad

**Comment by nickrandolph** [comment]
I've just tried this using latest commerce app on ipad and I can no longer repro this issue. Let's confirm this is fixed once the next version of the extensions template is released

**Comment by francoistanguay** [comment]
@kazo0  @nickrandolph  Can we close this?
