### ISSUE TITLE
[winui] Profile page crashes the app

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno.extensions#226]
## Current behavior

When opening the profile page, the app crashes:
![image](https://user-images.githubusercontent.com/5839577/145869243-4be4dd96-f474-4871-a395-c414f1736f80.png)

## How to reproduce it (as minimally and precisely as possible)

- Create an app from the unoapp-extensions template.
- Start the WinAppSDK package
- Open the profile tab

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by nickrandolph** [comment]
@jeromelaban I've just tested this in the latest commerce sample app running on WinUI in release mode and this issue appears to be fixed

**Comment by jeromelaban** [comment]
It is! Let's close this.
