### ISSUE TITLE
[MVUX] cast exception

### ISSUE THREAD

**Issue by dr1rrb** [unoplatform/uno.extensions#2274]
Remove `Unsafe.As<DispatcherQueueHandler>(action)`

**Comment by agneszitte** [comment]
(InvalidCastException on Windows can be reproduced on the [PongWars sample app here](https://github.com/unoplatform/Uno.Samples/pull/675) where the ItemsRepeater is not visible.

**Comment by agneszitte** [comment]
Related commit that fixes the issue: https://github.com/unoplatform/uno.extensions/commit/289de0d88187dc6aa3983f8721df81e15e080c9f
