### ISSUE TITLE
[Docs][Navigation] Some documentation/details at the moment are not used in the published documentation

### ISSUE THREAD

**Issue by agneszitte** [unoplatform/uno.extensions#2298]
Some documentation/details at the moment are not used in the published documentation.
They will need to be reviewed and adjusted to be added to the TOC for the Navigation documentation.
https://github.com/unoplatform/uno.extensions/blob/4919dca542fe9de3a66d3526c9b50ff4643702af/doc/toc.yml#L73-L89

**Comment by xperiandri** [comment]
Uncovered topics:
* What is the composite region?
* How to use `DependsOn` route parameter?

**Comment by agneszitte** [comment]
> Uncovered topics:
> 
> * What is the composite region?
> * How to use `DependsOn` route parameter?

@eriklimakc I will let you double-check for these topics please and if you can open separated issues if they are still not covered please
