### ISSUE TITLE
[Docs] Missing documentation on how to setup Uno.Extensions in an existing project

### ISSUE THREAD

**Issue by agneszitte** [unoplatform/uno.extensions#2321]
## What would you like clarification on
How to setup Uno.Extensions in an existing project

Similar to what we did for Uno.Themes/Uno.Toolkit here:
- https://platform.uno/docs/articles/external/uno.themes/doc/material-getting-started.html?tabs=wizard%2Csingleproj#installing-uno-material-in-an-existing-project
- https://platform.uno/docs/articles/external/uno.toolkit.ui/doc/material-getting-started.html?tabs=wizard%2Csingleproj#installing-uno-material-toolkit-in-an-existing-project

## Concern?
- [X] Getting started with Uno

## Additional info
At the same time, we should add proper tabs for Wizard Vs Cli when creating a solution for Uno.Extensions
Like for Uno.Themes/Uno.Tookit here:
- https://platform.uno/docs/articles/external/uno.themes/doc/material-getting-started.html?tabs=wizard%2Csingleproj#creating-a-new-project-with-uno-material
- https://platform.uno/docs/articles/external/uno.toolkit.ui/doc/material-getting-started.html?tabs=wizard%2Csingleproj#creating-a-new-project-with-the-uno-material-toolkit

Instead of having everything like this here:
https://platform.uno/docs/articles/external/uno.extensions/doc/GettingStarted.html#1-creating-the-app

**Comment by eriklimakc** [comment]
As discussed with @nickrandolph privately we're just adding instructions for Single Project template and guiding people to the Migrating to Single Project docs if they are using and older template.

The goal is to move all documents for extensions to just single project.

cc @agneszitte

**Comment by agneszitte** [comment]
> As discussed with @nickrandolph privately we're just adding instructions for Single Project template and guiding people to the Migrating to Single Project docs if they are using and older template.
> 
> The goal is to move all documents for extensions to just single project.
> 
> cc @agneszitte

@jeromelaban what do you think? 
We have details for legacy templates for other parts of the documentation for example:
- https://platform.uno/docs/articles/external/uno.themes/doc/material-getting-started.html?tabs=wizard%2Csingleproj#installing-uno-material-in-an-existing-project
- https://platform.uno/docs/articles/external/uno.toolkit.ui/doc/material-getting-started.html?tabs=wizard%2Csingleproj#installing-uno-material-toolkit-in-an-existing-project
- https://platform.uno/docs/articles/external/uno.extensions/doc/Learn/Maui/MauiOverview.html?tabs=single-project#mauiembedding-dependencies

So in my head Uno.Extensions documentation should at least give the same type of info for legacy templates, as not anyone can easily migrate or update in some context.

**Comment by jeromelaban** [comment]
If it's possible to keep the original content, sure. If not, let's go for single project.

**Comment by nickrandolph** [comment]
I think multi-head instructions are going to lead to a lot of confusion. With single project we can simply refer to Features, rather than the package references where it needs the .WinUI suffix in some cases, and not in others
