### ISSUE TITLE
Newly created Project with MSAL Authentication crashes 

### ISSUE THREAD

**Issue by AuderixDev** [unoplatform/uno.extensions#2356]
### Current behavior

When starting the WinAppSDK or Webassembly, from a newly created Uno Project with MSAL Authentication following Exception is thrown

```
Exception thrown: 'Microsoft.Identity.Client.MsalClientException' in Microsoft.Identity.Client.dll
Exception thrown: 'Microsoft.Identity.Client.MsalClientException' in System.Private.CoreLib.dll
```

Then the App shuts down immediately.

### Expected behavior

The project should start without Exceptions

### How to reproduce it (as minimally and precisely as possible)

The newly created project: https://github.com/AuderixDev/UnoAppSampleMSAL

Steps to reporduce:
- Create an Uno Project (Single Project) with Visual Studio Extension
- **Framework (default): NET 8.0**
- **Platforms: iOS + WebAssembly + Windows**
- Presentation (default): MVUX
- Markup (default): XAML
- Theme (default): Material + Theme Service + Import DSP
- Extensions (default): Dependency Injection, Configuration, HTTP, Localization, Regions, Default
- **Features: WASM Multi-Threading**, Toolkt, PWA Manifest, Visual Studio Code Debugging
- **Select Authentication: MSAL**

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly, Windows (WinAppSDK)

### IDE

Visual Studio 2022

### IDE version

17.9.6

**Comment by nickrandolph** [comment]
The exception itself indicates that the ClientId is missing. Whilst working on https://github.com/unoplatform/uno.extensions/pull/2355 it became evident that we can't validate whether a client id has been set as the ClientId property on the PublicClientApplicationBuilder isn't publically available.
@agneszitte can we make sure we add documentation for MSAL Authentication that warns about the need to have a client Id either set in appsettings.json or in code.

**Comment by agneszitte** [comment]
Documentation details updated with https://github.com/unoplatform/uno.extensions/pull/2368
