### ISSUE TITLE
[MVUX] Make all operators fluent friendly

### ISSUE THREAD

**Issue by dr1rrb** [unoplatform/uno.extensions#2398]
## What would you like to be added:
All operator (like `State.ForEachAsync` and `State.Observe`) should be fluent friendly so we don't have to declare them in ctor.

## Why is this needed:
To improve code discoverability and readability.

## For which Platform:

- [x] iOS
- [x] Android
- [x] WebAssembly
- [x] WebAssembly renders for Xamarin.Forms
- [x] Windows
- [ ] Build tasks

## Anything else we need to know?
This means that we need to enable caching like for other operators such as `Select`

**Comment by kazo0** [comment]
@dr1rrb / @ajpinedam can this be closed now due to https://github.com/unoplatform/uno.extensions/pull/2537?

**Comment by ajpinedam** [comment]
> @dr1rrb / @ajpinedam can this be closed now due to #2537?

Yes, please, this issue was duplicated, but it can be closed now (@kazo0 )
