### ISSUE TITLE
[Navigation] App is not launched if Navigation is used without Toolkit

### ISSUE THREAD

**Issue by agneszitte** [unoplatform/uno.extensions#2419]
### Current behavior

When creating a new Uno project with certain custom options detailed below, the application does not launch correctly or displays a blank screen on some platforms.

#### Summary of the options

![image](https://github.com/unoplatform/uno.extensions/assets/16295702/5e01e69d-bcce-4c65-8308-47f48dbfd398)

<details>
<summary>Written summary of the options (click here to expand)</summary>

**Framework**
- .NET 8.0

**Platforms**
- Android, iOS, WebAssembly, macOS (Catalyst), Windows, Desktop

**Presentation**
- MVVM

**Markup**
- XAML

**Theme**
- Material, Theme Service, Import Uno DSP

**Extensions**
- Dependency Injection, Configuration, Localization, Regions, Default

**Features**
- WASM Multi-Threading, PWA Manifest, Visual Studio Code Debugging

**Authentication**
- None

**CI Pipeline**
- None

</details>

#### Related dotnet new command to create a project with these options
`dotnet new unoapp -o UnoTestNavIssue -preset "recommended" -theme-service  -wasm-multi-threading  -theme "material" -presentation "mvvm" -config  -di  -log "default" -nav "regions" -http False -loc  -tests "none" -toolkit False -dsp  -id "com.companyname.UnoTestNavIssue" -pub "O=UnoPlatform"`

### Expected behavior

The application should launch and function correctly on all specified platforms with the given custom options.

### How to reproduce it (as minimally and precisely as possible)

1. Create a new Uno project using the custom options mentioned in the issue.
2. Launch the application on all platforms.
3. Observe that on some platforms, the application does not launch correctly or displays a blank screen on some platforms.

### Workaround

**Create a new sample solution:**
Select the **Toolkit** option in addition to the other options you chose previously.

**Update your existing solution:**
Follow the steps mentioned [here](https://github.com/unoplatform/uno.extensions/issues/2419):
- In your NameOfYourProject.csproj, add `Toolkit` to the `<UnoFeatures />`.
- In App.xaml.cs, add `.UseToolkitNavigation()` in the `OnLaunched` method:
```diff
var builder = this.CreateBuilder(args)
+    .UseToolkitNavigation()
     .Configure(host => host
....
```

### Works on UWP/WinUI

Yes

### Relevant plugins

N/A

### Anything else we need to know?

- Related Discord discussion: https://discord.com/channels/1182775715242967050/1182775715729526908/1260963886790742107
- Related sample app for the discussion used as a reference: [Uno.BrokenTestApp.zip](https://github.com/user-attachments/files/16181955/Uno.BrokenTestApp.zip)
- Same related sample app adjusted with the workaround as a reference: [Uno.BrokenTestApp-adjusted.zip](https://github.com/user-attachments/files/16183049/Uno.BrokenTestApp-ajusted.zip)

____

### Tested with Uno.Sdk 5.2 Stable
- Sample app created with Wizard
- Microsoft Visual Studio Professional 2022 (64-bit) - Current Version 17.10.1
- Uno Extensions version: 5.2.56.70
- Uno.Sdk: 5.2.175"
- UnoExtensionsVersion: 4.1.24
- UnoToolkitVersion: 6.0.24
- UnoThemesVersion: 5.0.13
- UnoCSharpMarkupVersion: 5.2.14
- Sample app used for the tests: [5.2 - UnoTestNavIssue.zip](https://github.com/user-attachments/files/16181142/UnoTestNavIssue.zip)

	#### Results:
	- ✅**Windows**: OK
	- ✅**Android**: OK
	- ❌**WASM**: Blank page
	- ❌**iOS**: Black screen
	- ❌**Desktop**: Console is launching but not the application
	- ❌**Desktop WSL2**: Empty window
	   ![image](https://github.com/unoplatform/uno.extensions/assets/16295702/8b6bdabd-5863-4fe4-9490-e3347dfdbf3a)
	   
____

### Tested with (Upcoming) Uno.Sdk 5.3 Stable
- Sample app created with Live Wizard + CLI
- Microsoft Visual Studio Professional 2022 (64-bit) - Current Version 17.10.4
- Uno.Templates: 5.3.24
- Uno.Sdk: 5.3.24
- Sample app used for the tests: [5.3 - UnoTestNavIssue.zip](https://github.com/user-attachments/files/16181119/UnoTestNavIssue.zip)

	#### Results:
	- ✅**Windows**: OK
	- ✅**Android**: OK
	- ✅**WASM**: OK
	- ❌**iOS**: Black screen
	- ❌**Desktop**: Console is launching but not the application
	- ✅**Desktop WSL2**: OK

**Comment by dansiegel** [comment]
This is not a template issue. If we create a project as @agneszitte showed then there is no Toolkit references in the project. From a Template perspective this is correct. This issue is that Navigation without Toolkit appears to be broken.

**Comment by metacoresystems** [comment]
I second the comment above. It is not a template issue, not even an extensions issue - the issue is that non-toolkit navigation is fundamentally broken.
