### ISSUE TITLE
ReadPackageFileAsync default template warnings

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno.extensions#2423]
## Current behavior

When running a default recommended template, the following errors show up:

```
warn: Uno.Extensions.Storage.FileStorage[0]
      ReadPackageFileAsync - File 'appsettings.keyvaluestorageconfiguration.json' does not exist in package
warn: Uno.Extensions.Storage.FileStorage[0]
      ReadPackageFileAsync - File 'appsettings.appconfig.json' does not exist in package
warn: Uno.Extensions.Storage.FileStorage[0]
      ReadPackageFileAsync - File 'appsettings.localizationconfiguration.json' does not exist in package
warn: Uno.Extensions.Storage.FileStorage[0]
      ReadPackageFileAsync - File 'appsettings.localizationsettings.json' does not exist in package
warn: Uno.Extensions.Storage.FileStorage[0]
      ReadPackageFileAsync - File 'appsettings.navigationconfiguration.json' does not exist in package
warn: Uno.Extensions.Navigation.Navigators.ContentControlNavigator[0]
      Show - Missing view for navigation path ''
```

These errors _may_ not be directly actionable, and the default recommended template should not show warnings.

## Expected behavior

No warnings.

## How to reproduce it (as minimally and precisely as possible)

Create and run a recommended template

## Environment

4.3.0-dev.5

**Comment by ArchieCoder** [comment]
@jeromelaban may I suggest all the following warnings to be changed to Debug so they don't show in log level Warning? None of them have call to action to do anything.

Uno.Extensions.Navigation.Navigators.ContentControlNavigator: Warning: Show - Missing view for navigation path ''
Uno.Extensions.Navigation.Navigators.ContentControlNavigator: Show - Missing view for navigation path '' 
Uno.Extensions.Navigation.Navigators.ContentControlNavigator: CreateControlFromType - Creating control of type FrameView 
Uno.Extensions.Navigation.Navigators.FrameNavigator: NavigateAsync - Starting Navigation - Navigator: FrameNavigator Request: Main 

Microsoft.UI.Xaml.UIElement: Warning: The ManipulationMode 'TranslateX, TranslateY, TranslateInertia' is not supported by Uno. Only 'None', 'All', 'System', 'TranslateX', 'TranslateY', 'Rotate', and 'Scale' are supported. Using any other mode will not cause an error, but the corresponding manipulation event will not be generated. Note that with Uno the 'All' and 'System' are handled the same way.

Microsoft.UI.Xaml.UIElement: The ManipulationMode 'TranslateX, TranslateY, TranslateInertia' is not supported by Uno. Only 'None', 'All', 'System', 'TranslateX', 'TranslateY', 'Rotate', and 'Scale' are supported. Using any other mode will not cause an error, but the corresponding manipulation event will not be generated. Note that with Uno the 'All' and 'System' are handled the same way. 

I/Uno.Extensions.Navigation.Navigators.PanelVisiblityNavigator: CreateControlFromType - Creating control of type DirectConnectionControl 

I/Microsoft.UI.Xaml.UIElement: Microsoft.UI.Xaml.Controls.Button: no pointers to release. 

I/Uno.Extensions.Navigation.Navigators.FrameNavigator: NavigateAsync - Starting Navigation - Navigator: FrameNavigator Request: Main/Debug 

I/Microsoft.UI.Xaml.UIElement: Microsoft.UI.Xaml.Controls.Button: Cannot release pointer Mouse/1: not captured by this control.

**Comment by jeromelaban** [comment]
@ArchieCoder We're chasing those as well, @Darsh0307 will create issues.
