### ISSUE TITLE
[HTTP] Add support for Kiota

### ISSUE THREAD

**Issue by kazo0** [unoplatform/uno.extensions#2459]
This random guy blogged about using Kiota: https://nicksnettravels.builttoroam.com/kiota-gettingstarted/

We could have Kiota extension support that could replace the Refit support in Extensions

**Comment by kazo0** [comment]
See what we did with Refit: exception handling, logging, etc. HttpClient customization

**Comment by kazo0** [comment]
Auth: https://learn.microsoft.com/en-us/openapi/kiota/authentication?tabs=csharp
Middleware: https://learn.microsoft.com/en-us/openapi/kiota/middleware
Error Handling: https://learn.microsoft.com/en-us/openapi/kiota/errors

**Comment by agneszitte** [comment]
Tracking will continue with https://github.com/unoplatform/uno.extensions/issues/2510
