### ISSUE TITLE
Tokens can't be retrieved after successful login

### ISSUE THREAD

**Issue by nickrandolph** [unoplatform/uno.extensions#2470]
## Current behavior

After signing in using web authentication, restarting the application required user to login again because tokens can't be retrieved

## Expected behavior

After authenticating, next run of application should use the existing tokens to attempt to refresh tokens

## Environment

Nuget Package (s):

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] macOS (AppKit)
- [ ] Mac Catalyst
- [ ] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Skia (WPF)
- [ ] Skia (GTK on Linux/macOS/Windows)
- [ ] Skia (Linux Framebuffer)
- [ ] Build tasks

Visual Studio:

- [ ] 2019 (version: )
- [ ] 2022 (version: )
- [ ] Visual Studio Code (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by agneszitte** [comment]
@nickrandolph do we have an easy way to QA these changes?
