### ISSUE TITLE
[Windows] Crash when adding items from MVUX model to a ListState

### ISSUE THREAD

**Issue by kazo0** [unoplatform/uno.extensions#2474]
- **Windows**: 
still crashing when trying to add elements to the collection
 _System.Runtime.InteropServices.COMException: ErrorCode -2147417842_

_Originally posted by @kucint in https://github.com/unoplatform/uno.extensions/issues/2428#issuecomment-2247106356_

**Comment by kazo0** [comment]
@kucint / @MartinZikmund 

This seems to be an issue with the sample code trying to update a property on the wrong thread. I see `Microsoft.ui.xaml.dll!00007FF8A01E0713: 8001010E - RPC_E_WRONG_THREAD` in the output where it crashes

**Comment by kazo0** [comment]
Alright, the problem is that when adding a new Item we are initializing a new `SolidColorBrush` while we are on the background thread. The `Dispatcher` will need to be used to run that logic on the UI thread

**Comment by kucint** [comment]
indeed, I did not realize that SolidColorBrush is in fact dependency object.

**Comment by kazo0** [comment]
@kucint / @MartinZikmund 

I will close this one as a duplicate of https://github.com/unoplatform/uno.extensions/issues/2455
