### ISSUE TITLE
[Authentication][MSAL] API surface differs between tfms

### ISSUE THREAD

**Issue by kazo0** [unoplatform/uno.extensions#2484]
As of [this](https://github.com/unoplatform/uno.extensions/commit/14979905a3a4c35a2f72a546d3471ffa32da6bb9), we now need to wrap the MSAL builder calls with `UNO_EXT_MSAL`. Like we are doing in the [TestHarness](https://github.com/unoplatform/uno.extensions/blob/fbe8ccf3f18eef69b5acff868e1cc38d8151f5c9/testing/TestHarness/TestHarness.Shared/Ext/Authentication/Msal/MsalAuthenticationMultiHostInit.cs#L106).

We should document the platforms that are/are not supported and highlight the usage of `UNO_EXT_MSAL` in the [MSAL How-to docs](https://github.com/unoplatform/uno.extensions/blob/fbe8ccf3f18eef69b5acff868e1cc38d8151f5c9/doc/Learn/Authentication/HowTo-MsalAuthentication.md)

**Comment by jhanvi03** [comment]
Tested MSAL on VS with Uno.sdk &  template 5.3.112
Test Result:
Passed for WebAssembly, WebAssemblyIISExpress
WinAppSDKPackaged: Back Button is not visible on Login page
Android: HR not getting connected( error message on HR indicator: timeout)
