### ISSUE TITLE
[MSAL] Back button is not visible for WinAppSDK Packaged

### ISSUE THREAD

**Issue by jhanvi03** [unoplatform/uno.extensions#2560]
## Current behavior

When a Project is created for MSAL and launching solution for WinAppSDK Packaged, the back button is not visible. The back button is visible on WebAssembly, WebAssembly IIS Express, Android. Found the issue while testing Uno.SDK & template 5.3.112 but the issue is also present with 5.3.108.
![Screenshot 2024-09-20 at 4 03 32 PM](https://github.com/user-attachments/assets/32dd6293-cba5-4e3d-818e-10344bc2a735)

## Expected behavior
The back Icon should be visible for WinAppSDK ass well

![Screenshot 2024-09-20 at 4 01 29 PM](https://github.com/user-attachments/assets/aa43b2ef-caad-4c68-82ae-274aa8c6f236)

## How to reproduce it (as minimally and precisely as possible)

1. Open VS
2. Create a new uno project. 
3. From the Wizard uncheck MacCatalyst and Desktop (inorder to enable MSAL).
4. Check MSAL from the authentication.
5. Click on create project.
6. Select WinAppSDK as a target solution
7. Build the Solution
8. Observe the missing Back Button\icon.

## Environment

Nuget Package (s):
Uno.SDK & Template verison: 5.3.108, 5.3.112
Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] macOS (AppKit)
- [ ] Mac Catalyst
- [ ] Android
- [ ] WebAssembly
- [x] Windows
- [ ] Skia (WPF)
- [ ] Skia (GTK on Linux/macOS/Windows)
- [ ] Skia (Linux Framebuffer)
- [ ] Build tasks

Visual Studio:

- [ ] 2019 (version: )
- [ ] 2022 (version: )
- [ ] Visual Studio Code (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

Found issue while testing https://github.com/unoplatform/uno.extensions/issues/2484 for https://github.com/unoplatform/private/issues/528

**Comment by agneszitte** [comment]
fyi @kazo0

**Comment by kazo0** [comment]
This may have been fixed by https://github.com/unoplatform/uno.toolkit.ui/pull/1228

**Comment by Kunal22shah** [comment]
![image](https://github.com/user-attachments/assets/2b495f3f-0fe9-4b2e-bc8f-0fda150b9e8e)
It has been fixed now.

**Comment by jhanvi03** [comment]
Able to see the back button/icon. Tested with sdk/template 5.5.24 & VS VSIX 5.5.30.

<img width="928" alt="Screenshot 2024-10-28 at 10 27 51 PM" src="https://github.com/user-attachments/assets/93e9b954-869b-4018-a1fd-d3855e405b65">
<img width="1060" alt="Screenshot 2024-10-28 at 10 27 30 PM" src="https://github.com/user-attachments/assets/f8e6085a-2636-47da-81e2-96d1e888f64a">
