### ISSUE TITLE
Missing NuGet packages for Uno.Extensions.Templates::1.1.0

### ISSUE THREAD

**Issue by DarkDaskin** [unoplatform/uno.extensions#279]
I followed instructions on the README and got a project which references package versions which do not exist.

Running `dotnet new -i Uno.Extensions.Templates` installs templates of version 1.1.0 which reference NuGet packages of the same version, but on NuGet only version 1.0.1 is published as well as some preview versions.

Installing older version of the templates by running `dotnet new -i Uno.Extensions.Templates::1.0.1` does not have the same problem.

**Comment by nickrandolph** [comment]
Hey @DarkDaskin thanks for the feedback - we're always trying to improve the process for pushing out new builds. If you have a chance, can you try the latest preview version (https://www.nuget.org/packages/Uno.Extensions.Templates/1.2.0-dev.189) and let us know if this issue continues.

**Comment by nickrandolph** [comment]
Closing this issue as the latest dev template has the correct packages referenced
