### ISSUE TITLE
[WASM[Commerce App]  Checkout title is duplicated and the Done button isn't in the right spot.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno.extensions#291]
## Current behavior
![commerce checkout](https://user-images.githubusercontent.com/74563602/156235413-01b2f7f5-a7cb-4c34-9e11-d082fe8ec455.png)

## Expected behavior
The Checkout title should not be duplicated and Done button should be on the right spot.

## How to reproduce it (as minimally and precisely as possible)

1. Launch the Commerce App Sample
2. Login
3. Navigate to the Cart tab
4. Click on the Checkout option.
5. Notice that the Checkout title is duplicate and Done button is not on the right spot.

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

**Comment by nickrandolph** [comment]
@francoistanguay is there someone who can assist with providing a design for this page. Alternatively we could remove the second page in the cart for the timebeing?

**Comment by francoistanguay** [comment]
Let's remove it for now.
