### ISSUE TITLE
[WASM[Commerce App] Filters- The 'In Stock Only' Toggleswitch in Enabled position is not properly visible in Light mode.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno.extensions#292]
## Current behavior

![Toggleswitch](https://user-images.githubusercontent.com/74563602/156238136-1c32a405-8fe3-4df4-83ca-9ae67382221a.png)

## Expected behavior
The 'In Stock Only' Toggleswitch should properly visible in Light mode.

## How to reproduce it (as minimally and precisely as possible)
1. Launch the Commerce App Sample
2. Login
3. Navigate to the Product tab.
4. Click on the Filters option.
5. Enable 'In stock only' Toggleswitch.
6. Notice that the toggleswitch is not properly visible in day mode.

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

**Comment by francoistanguay** [comment]
What is NOT visible? The pale blue?

**Comment by sakshi173** [comment]
Yes the color of the toggleswitch.

**Comment by francoistanguay** [comment]
This is the sample theme and we wont change it. I get that Pale blue on Gray is not super visible but that's fine.
