### ISSUE TITLE
Not all Extensions packages are being published

### ISSUE THREAD

**Issue by nickrandolph** [unoplatform/uno.extensions#469]
Some of the extensions packages aren't being pushed to NuGet. 

For example, currently the latest release is 1.2.0-dev.732 eg
https://www.nuget.org/packages/Uno.Extensions.Configuration/1.2.0-dev.732

but, this version doesn't exist for Reactive.WinUI or Serialization eg
https://www.nuget.org/packages/Uno.Extensions.Reactive.WinUI/1.2.0-dev.710
https://www.nuget.org/packages/Uno.Extensions.Serialization/1.2.0-dev.710

**Comment by jeromelaban** [comment]
This is caused by the new package that was added, let me fix that.

**Comment by jeromelaban** [comment]
Done!
