### ISSUE TITLE
[template] The .vsconfig is installing too many workloads

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno.extensions#515]
See the latest workload list from the uno vsix template. (net4x and related don't need to be installed)

**Comment by nickrandolph** [comment]
I was taking a look at both the dotnet new templates and the VSIX to work out which .vsconfig to use and there seems to be a few options. Currently I've used the VS Ext (v17) but not sure if this is best, particularly for net6

unoapp-net6: https://github.com/unoplatform/uno/blob/master/src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-net6/.vsconfig
unoapp-winui: https://github.com/unoplatform/uno/blob/master/src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-winui/.vsconfig
unoapp-winui-net6: https://github.com/unoplatform/uno/blob/master/src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-winui-net6/.vsconfig

VS Ext (v17): https://github.com/unoplatform/uno/blob/master/src/SolutionTemplate/UnoSolutionTemplate.Wizard.2022/.vsconfig.vs17

**Comment by nickrandolph** [comment]
@jeromelaban can you point to which of the .vsconfig files we should use?
