### ISSUE TITLE
[Navigation] Commerce sample, Login page not shown when using specific Shell view

### ISSUE THREAD

**Issue by ttustonic** [unoplatform/uno.extensions#519]
## On which page?
Login page

## What's wrong?
I try to change ViewMap registration for ShellViewModel, to include specific View:
`new ViewMap(View: typeof(ShellPage), ViewModel: typeof(ShellViewModel)),`

My test ShellPage is very simple:
```
<Page...>
    <Frame  />
    <!-- uen:Region.Attached="True"  makes no difference --> 
</Page>
```
When I start the Windows Desktop app it only shows an empty white page.
Default ViewMap registration works fine.

Is this supported, and if yes, what am I missing?

Thanks, Tom

**Comment by nickrandolph** [comment]
The latest extensions template (see https://www.nuget.org/packages/Uno.Extensions.Templates/2.1.0-dev.70) uses ShellControl (which is a user control). I think using a Page as the root will attempt to inject an additional frame which is undesirable (and probably results in the issue you're seeing)

**Comment by nickrandolph** [comment]
Hi Tom,

Shell view is definitely supported but I'm guessing something's not setup correctly. If you grab the dotnet new templates and then run
`dotnet new unoapp-extensions-net6 -o MyApp`
This should create a new app that has a ShellControl at the root

**Comment by ttustonic** [comment]
Thanks for the reply
I tried with a new application from the template and it works fine.
However, I modified it a bit to include a few login parts from the Commerce app, and it's the same.

When I use line:
```new ViewMap(ViewModel: typeof(ShellViewModel)),```
it shows a login page, but when I use 
```new ViewMap<ShellControl,ShellViewModel>()```
it doesn't

It seems that the problem is in the login process/navigation.

Cheers, Tom

[MyAppOLD.zip](https://github.com/unoplatform/uno.extensions/files/8887030/MyAppOLD.zip)

**Comment by nickrandolph** [comment]
@ttustonic looks like there's a bug when you use the ShellControl with clearing the backstack. Change the navigation call in ShellViewModel to remove the "Qualifiers.ClearBackStack" eg
var response = await Navigator.NavigateForResultAsync<Credentials>(this);

**Comment by ttustonic** [comment]
Sorry for delay...
Yes, this works, thanks.

**Comment by ttustonic** [comment]
Too early... :(
I tried again with the latest download of Extensions and a Commerce sample.
When I remove `ClearBackStack`, it shows login page, but after login it seems to go back to the Login control, after a call to `DoLogin `in the `LoginViewModel`.
I also tried to remove ClearBackStack from the
`_navigator.NavigateDataAsync(this, currentCredentials, Qualifiers.ClearBackStack);`
line, but in that case it shows the app UI, but just enters in some kind of loop and nothing works.
Attached is a debug output for the login proces

[loginlog.txt](https://github.com/unoplatform/uno.extensions/files/8936405/loginlog.txt)

**Comment by nickrandolph** [comment]
@ttustonic can you confirm whether this issue is still present in the latest release of the navigation extensions? If it is, I'll make sure this gets some attention this week

**Comment by ttustonic** [comment]
Hmm, unfortunately, no.

It looks the same as before.
I downloaded a latest Commerce sample, updated all *Extensions* packages to version 2.2.0-dev.8, and it's still the same.

- When using a custom `ShellControl `(with just a Frame and attached Region) with `ShellViewModel`, Login page is not shown. Log is in the defaultlog.txt
- When removing `Qualifiers.ClearBackStack` from a call to `NavigateForResultAsync` Credentials are saved, but it just goes back to the login page. Log is in the loginlog.txt
- When removing `Qualifiers.ClearBackStack` from a call to `NavigateDataAsync` it goes into a loop. Log is in the looplog.txt

Cheers, Tom

[logs.zip](https://github.com/unoplatform/uno.extensions/files/9098451/logs.zip)
[App.xaml.host.cs.zip](https://github.com/unoplatform/uno.extensions/files/9098466/App.xaml.host.cs.zip)
[ShellControl.zip](https://github.com/unoplatform/uno.extensions/files/9098468/ShellControl.zip)

**Comment by nickrandolph** [comment]
@ttustonic replace
```csharp
// Enable navigation, including registering views and viewmodels
				.UseNavigation(
					RegisterRoutes,
					createViewRegistry: sc => new ReactiveViewRegistry(sc, ReactiveViewModelMappings.ViewModelMappings),
					configure: cfg => cfg with { AddressBarUpdateEnabled = true })
				.ConfigureServices(services =>
				{
					services
						.AddSingleton<IRouteResolver, ReactiveRouteResolver>();
				})
```
with 

```csharp
.UseNavigation(MyAppOLD.ReactiveViewModelMappings.ViewModelMappings, RegisterRoutes)
```
