### ISSUE TITLE
[Navigation] Installing Uno.Extensions.Navigation.Toolkit.UI in UWP project breaks the build

### ISSUE THREAD

**Issue by HakanL** [unoplatform/uno.extensions#563]
## Current behavior

I have a simple Uno app (created from templates) where I'm trying to have both UWP and WinUI available concurrently (using if defs). I got most of it working, can even view Xaml pages in the designer. But when I try to Add the Nuget package Uno.Extensions.Navigation.Toolkit.UI the build is failed (no real error message, it just says this:
Could not copy the file "C:\Users\hakan\.nuget\packages\uno.extensions.navigation.toolkit.ui\2.1.0-dev.192\lib\uap10.0.18362\Uno.Extensions.Navigation.UI\Uno.Extensions.Navigation.UI.xr.xml" because it was not found.	App3.UWP			

I have tried with version 2.0.0 and 2.1.0-dev.192, same issue. If I remove the Nuget package from the UWP head then it builds and runs fine.

## Expected behavior

Build should be successful.

## How to reproduce it (as minimally and precisely as possible)

https://github.com/HakanL/UnoMultiPlatform1

## Environment

Nuget Package:
Uno.Extensions.Navigation.Toolkit.UI

Package Version(s):
2.0.0 and 2.1.0-dev.192

Affected platform(s):

- [X] UWP

Visual Studio:

- [X] 2022

Relevant plugins:

- [ ] Resharper (version: )

**Comment by nickrandolph** [comment]
@HakanL I'll review this and provide update asap

**Comment by nickrandolph** [comment]
cc @kazo0

**Comment by kazo0** [comment]
Just an update to say that we are still actively looking into this, haven't found the cause yet.

**Comment by nickrandolph** [comment]
This has been fixed and the update is available in the latest dev release of the Uno.Navigation.Toolkit.UI package
