### ISSUE TITLE
[Navigation] Need samples for Back button and Settings in the NavigationView

### ISSUE THREAD

**Issue by ttustonic** [unoplatform/uno.extensions#570]
## What would you like to be added:

It would be nice to see a working example for a Settings and Back button in the NavigationView control.
Both Playground and Commerce samples hide the Settings item and BackButton, and when enabled, they don't seem to work.

## For which Platform:

- [x] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly Renderers for Xamarin.Forms
- [x] Windows

**Comment by nickrandolph** [comment]
@ttustonic I'll try to get a sample for this done this week.
