### ISSUE TITLE
[Reactive] AsyncPaginated with ListState

### ISSUE THREAD

**Issue by thierry-fortin1** [unoplatform/uno.extensions#627]
## What would you like to be added:
The AsyncPaginated function for the ListState class.

## Why is this needed:
I currently have a ListFeed (Messages) linked with the UI to show items in a ListView.
I also have a ListState (_stateMessages) to receive the IMessenger notifications when I add items dynamically.
The problem is that I can't link both so that when I add an item in the ListState, it also updates the ListFeed (so the UI).

I could just use the ListState as the databinder in the xaml, but it wouldn't work since there's no AsyncPaginated on ListState.
![image](https://user-images.githubusercontent.com/105242267/182948951-b9a70f59-eac0-43ce-955e-349dde556018.png)

## For which Platform:

- [X] iOS
- [X] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [X] Windows
- [ ] Build tasks

## Anything else we need to know?
I have tested several other options involving ListState and ListFeed, but none really works. I am on version 2.2.0-dev.77 of Uno.Extensions.Reactive, Reactive.WinUI and Reactive.Core.

**Comment by dr1rrb** [comment]
This has been implemented
