### ISSUE TITLE
Default .NET Template UITest Fails to Run Test

### ISSUE THREAD

**Issue by SkyeHoefling** [unoplatform/uno.extensions#640]
## Current behavior
When creating a new project using the .NET CLI `dotnet new unoapp-extensions` the UI Tests will not work out of the box. This is because the `NUnit3TestAdapter` has a known issue in `4.2.1` where it will always have an exception when running the tests
```
The type initializer for 'NUnit.Engine.Services.RuntimeFrameworkService' threw an exception.
   at NUnit.Engine.Services.RuntimeFrameworkService.ApplyImageData(TestPackage package)
   at NUnit.Engine.Services.RuntimeFrameworkService.SelectRuntimeFramework(TestPackage package)
   at NUnit.Engine.Runners.MasterTestRunner.GetEngineRunner()
   at NUnit.Engine.Runners.MasterTestRunner.Explore(TestFilter filter)
   at NUnit.VisualStudio.TestAdapter.NUnitEngine.NUnitEngineAdapter.Explore(TestFilter filter) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnitEngine\NUnitEngineAdapter.cs:line 88
   at NUnit.VisualStudio.TestAdapter.NUnit3TestExecutor.RunAssembly(String assemblyPath, IGrouping`2 testCases, TestFilter filter) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnit3TestExecutor.cs:line 275
InnerException: System.ArgumentException: Unknown framework version 7.0
```

This issue is fully documented with a workaround https://github.com/nunit/nunit3-vs-adapter/issues/987

## Expected behavior

When right-click on the UITest project it should run the tests correctly

## How to reproduce it (as minimally and precisely as possible)
[ReproductionProject.zip](https://github.com/unoplatform/uno.extensions/files/9284143/ReproductionProject.zip)

1. Download the reproduction project or generate a fresh project using `dotnet new unoapp-extensions` using version `2.1.1`
2. Open with Visual Studio
3. Launch the WASM project without debugging by setting as startup and tapping `ctrl` + `F5`
4. Open the Visual Studio Text Explorer
5. Run UI Tests

## Environment

Nuget Package: Uno.Extensions.Templates

Package Version(s): 2.1.1

Affected platform(s):

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [x]  2022 (version: 17.2.5)
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?
I was able to follow the NUnit VS Adapter discussion in https://github.com/nunit/nunit3-vs-adapter/issues/987 and update the test adapter to a preview build. Looks like it is the recommended approach as .NET 7 gets closer to GA. See exact comment https://github.com/nunit/nunit3-vs-adapter/issues/987#issuecomment-1167814552

**PR is incoming**

**Comment by nickrandolph** [comment]
I don't think the issue is with the test adapter, there's a line of code missing in the template to instruct the UITests to not run in headless mode in debug.
Fixed here: https://github.com/unoplatform/uno.extensions/blob/11efd7dda5ed6f441af2f7cddaa23aeb9b2a3afd/src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.UITests/TestBase.cs#L18-L20
