### ISSUE TITLE
[UI] Arrow icon doesn't show on windows 

### ISSUE THREAD

**Issue by DiegoBillares** [unoplatform/uno.extensions#727]
## Current behavior

utu:NavigationBar doesn't show the arrow icon on windows. You can come back to the last page but the back button doesn't have any content.

## Expected behavior

The utu:NavigationBar shows an arrow icon on back button. 

## How to reproduce it (as minimally and precisely as possible)

- Open app
- Click on navigation button to go the next page

## Environment

Nuget Package: Uno.Toolkit.WinUI

Package Version(s): 2.4.0-dev.5

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [x] Windows
- [ ] Build tasks

Visual Studio:

- [x] 2022 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

[EmptySampleApp.zip](https://github.com/unoplatform/uno.extensions/files/9567794/EmptySampleApp.zip)

**Comment by kazo0** [comment]
This is currently a limitation of the Uno.Toolkit.UI library. We do not have a default image asset that the `MainCommand` can use as its `AppBarButton.Icon`. 

We can track the options/workarounds [here](https://github.com/unoplatform/uno.toolkit.ui/issues/321)
