### ISSUE TITLE
[Localization] Localization don't take language from phone by default

### ISSUE THREAD

**Issue by DiegoBillares** [unoplatform/uno.extensions#782]
## Current behavior
The app always take english language, if you have your phone set with french language, the app doesn't change to french too.

## Expected behavior
The app should take phone language by default.

## How to reproduce it (as minimally and precisely as possible)

- Don't put english language on your phone because it's the default. For example, change phone language to french
- Open the app

## Environment

Nuget Package: Uno.Extensions.Localization.WinUI

Package Version(s): 2.3.0-dev.69

Affected platform(s):

- [x] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [x] 2022 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?
[EmptySampleApp.zip](https://github.com/unoplatform/uno.extensions/files/9687798/EmptySampleApp.zip)

**Comment by nickrandolph** [comment]
@DiegoBillares this has been fixed and should be available with the next dev release of Uno.Extensions. You need to make sure you reference Uno.Extensions.Localization.UI if you're still using xamarin/uwp target platforms. This package doesn't exist yet on nuget, but will do after the next release
