### ISSUE TITLE
[Reactive] [Android] Scroll focus is sometimes lost on horizontal listview

### ISSUE THREAD

**Issue by DiegoBillares** [unoplatform/uno.extensions#789]
## Current behavior
Refreshcontainer, controls:ExtendedRefreshContainer produce the horizontal listview gets stuck when you try to do horizontal scrolling.

## Expected behavior
Normal flow when it's scrolling through listview items horizontally.

## How to reproduce it (as minimally and precisely as possible)

- Open the app 
- Scroll horizontal listview

## Environment

Nuget Package: Uno.Extensions.Reactive.UI

Package Version(s): 2.3.0-dev.69

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [x] 2022 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?
[EmptySampleApp.zip](https://github.com/unoplatform/uno.extensions/files/9700873/EmptySampleApp.zip)

Videos:

https://user-images.githubusercontent.com/94696299/193679587-c484ea67-6edb-433f-a040-d5363071f3df.mp4

https://user-images.githubusercontent.com/94696299/193679652-44208a63-f009-4719-bacd-4ca70dd96c33.mp4

**Comment by MartinZikmund** [comment]
Fixed in Uno
