### ISSUE TITLE
UnoHost.CreateDefaultBuilder() throws InvalidOperationException on unpackaged WinUI3

### ISSUE THREAD

**Issue by hygehyge** [unoplatform/uno.extensions#802]
## Current behavior

As the title says.

## Expected behavior

Doesn't throw Exception.

## How to reproduce it (as minimally and precisely as possible)

1. Add `<WindowsPackageType>None</WindowsPackageType>` to Uno.Windows.csproj. 
2. Add a package reference to `Uno.Extensions.Hosting.WinUI`.
3. In `App.xaml.cs`, write as follows.
```csharp
public IHost Host { get; init; }

public App()
{
      this.Host = UnoHost
          .CreateDefaultBuilder() //<- this line throws InvalidOperationException
          .Build();

      InitializeLogging();

      this.InitializeComponent();

#if HAS_UNO || NETFX_CORE
      this.Suspending += OnSuspending;
#endif
}
...
```

## Environment

Nuget Package:Uno.Extensions.Hosting.WinUI

Package Version(s):2.2.0

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [x] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [x] 2022 (version: 17.3.5)
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

I think this happens because unpackaged app doesn't have package identity. (of cource.)
In `UnoHost` class, you create `AppHostingEnvironment` like below.
```csharp
AppHostingEnvironment.FromHostEnvironment(ctx.HostingEnvironment, Windows.Storage.ApplicationData.Current.LocalFolder.Path);
```
And `Windows.Storage.ApplicationData` is listed on [apis-that-require-package-identity](https://learn.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-supported-api#apis-that-require-package-identity).

I'm newbie on Uno platform.
Is this a known limitation?  Does Uno support unpackaged WinUI?

**Comment by nickrandolph** [comment]
Thanks for raising this. At this stage we haven't tested against unpackaged WinUI apps. We'll endeavour to add this to the documentation and schedule work to test for unpackaged apps

**Comment by hygehyge** [comment]
@nickrandolph 
Why has this been closed as completed?
Is there some improvement?
If so, please let me know.
