### ISSUE TITLE
[Localization] Localization doesn't take language from phone by default

### ISSUE THREAD

**Issue by DiegoBillares** [unoplatform/uno.extensions#804]
## Current behavior

The app always take english language, if you have your phone set with french language, the app doesn't change to french too.

## Expected behavior

The app should take phone language by default.

## How to reproduce it (as minimally and precisely as possible)

- Don't put english language on your phone because it's the default. For example, change phone language to french
- Open the app

## Environment

Nuget Package: Uno.Extensions.Localization.WinUI

Package Version(s): 2.3.0-dev.112

Affected platform(s):

- [x] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [x] 2022 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?
[EmptySampleApp.zip](https://github.com/unoplatform/uno.extensions/files/9765857/EmptySampleApp.zip)

Observations: 

I saw the last update on LanguageService into this extension, and I tried to modify the LocalizationConfiguration->Cultures into appsettings.json where I added an object with "Name" property something like this: 

"LocalizationConfiguration": {
    "Cultures": [ { "Name":"en" }, { "Name":"fr" } ]
  }

When I made this change, everything worked good, although it keeps this change impact a lot on our solution. I thought about this change because of the following lines of code:

https://github.com/unoplatform/uno.extensions/blob/a507242625c6f4f185226e67092cac9f135c0c29/src/Uno.Extensions.Localization.UI/LocalizationService.cs#L31

Our solution works with the normal way like this: 

"LocalizationConfiguration": {
    "Cultures": [ "en", "fr"]
  }

**Comment by nickrandolph** [comment]
Please change the Build Action on you appsettings.json and appsettings_platform_development.json to Embedded Resource.

Also, if you only want to have a development version of appsettings, you can remove the ".EmbeddedSource<App>("platform"))" line from you host setup and change the name of the file to appsettings.development.json
