### ISSUE TITLE
[Storage] Content files that are in a sub-folder aren't accessible on Android

### ISSUE THREAD

**Issue by nickrandolph** [unoplatform/uno.extensions#927]
## Current behavior

If you have a Content file in a sub-folder (eg /Assets/MyPhoto.png ) you can't access it via IStorage interface on Android. This is because of the logic added to cache the index of files which only retrieves the list at the root folder level.

## Expected behavior

Content in sub-folders should be accessible

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Asset files are only accessible through the https://platform.uno/docs/articles/features/file-management.html?q=storage#support-for-storagefilegetfilefromapplicationuriasync. Is this how you're getting the files?
