### ISSUE TITLE
[Android] Uno.Extensions.Navigation.RouteResolverDefault.LoadedTypes is expensive

### ISSUE THREAD

**Issue by ebariche** [unoplatform/uno.extensions#958]
![image](https://user-images.githubusercontent.com/33458222/205164610-d54fff7d-fef0-4443-a09e-15b92fa78df2.png)

**Comment by jeromelaban** [comment]
@nickrandolph it's likely that creating a generator that populates that list at compile time will solve this issue (at least as long a the searched types are not loaded dynamically).

**Comment by nickrandolph** [comment]
yeh this has long been the goal but wasn't a priority since devs really need to generate routemaps for more complex scenarios like tabs anyhow. In this case there are routes defined, so I'll need to review to work out why it's not picking those up

**Comment by nickrandolph** [comment]
@ebariche I was just investigating this further and the original app ([here](https://github.com/unoplatform/uno.extensions/issues/976)) doesn't invoke LoadedTypes, so I'm not sure why it's appearing in the performance testing you were doing. Can we sync to discuss this?

**Comment by nickrandolph** [comment]
I'm going to close this as we've validated that LoadedTypes only gets invoked if routes aren't defined, and there's a warning in debug console if this method is called.
