### ISSUE TITLE
[WinUI] Sometimes we get stuck in the splashScreen

### ISSUE THREAD

**Issue by Marc-Antoine-Soucy** [unoplatform/uno.extensions#969]
## Current behavior
When reopening the app after closing it, and after the refresh token expired, the app gets stuck in the splashscreen. To get to the login screen, you need to uninstall the app and reinstall it. 

## Expected behavior
The app shouldn't get stuck in the splashscreen.

## Environment

Nuget Package:
Uno.Extensions.Authentication" Version="2.3.0-dev.256" />
Uno.Extensions.Configuration
Uno.Extensions.Core
Uno.Extensions.Hosting
Uno.Extensions.Hosting.WinUI
Uno.Extensions.Http
Uno.Extensions.Http.Refit
Uno.Extensions.Localization.WinUI
Uno.Extensions.Logging.Serilog
Uno.Extensions.Logging.WinUI
Uno.Extensions.Navigation.Toolkit.WinUI
Uno.Extensions.Navigation.WinUI
Uno.Extensions.Navigation
Uno.Extensions.Serialization
Uno.Extensions.Serialization.Refit
Uno.Extensions.Reactive
Uno.Extensions.Reactive.WinUI

Package Version(s):

Version="2.3.0-dev.256" 

Affected platform(s):

- [ ] iOS ~Maybe sometimes?/ On some versions of IOS?
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [X] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [X] 2022 (version: 17.4.1)
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by Marc-Antoine-Soucy** [comment]
@nickrandolph

**Comment by nickrandolph** [comment]
@Marc-Antoine-Soucy I've tried to reproduce this and have been unable to. 
If you're still seeing this, let me know and we can investigate in the context of an actual app
