### ISSUE TITLE
[Reactive] .CollectionChanged from a collection Feedview is called on the wrong thread.

### ISSUE THREAD

**Issue by Marc-Antoine-Soucy** [unoplatform/uno.extensions#970]
## Current behavior

When trying to get the notification from the collection changed based on a feed, we get to the wrong thread which crashes the app.

## Expected behavior

It should still be in the main thread if the changes come from the main thread.

## How to reproduce it (as minimally and precisely as possible)

[App8.zip](https://github.com/unoplatform/uno.extensions/files/10155641/App8.zip)

The repro app currently is not working because it does not implement INotifyCollectionChanged or ICollectionView. But I'm not sure why it doesnt. I will modify it later as necessary.
## Environment

Nuget Package:

Package Version(s):

		`<PackageReference Include="Microsoft.WindowsAppSDK" Version="1.1.3" />
		<PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.22621.755" />
		<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="5.0.0" />
		<PackageReference Include="Uno.Core.Extensions.Logging.Singleton" Version="4.0.1" />
		<PackageReference Include="Uno.Extensions.Reactive.WinUI" Version="2.3.0-dev.359" />`
Affected platform(s):

- [X] iOS
- [X] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [X] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [X] 2022 (version: 17.4.1)
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by Marc-Antoine-Soucy** [comment]
@dr1rrb

**Comment by dr1rrb** [comment]
This should have been fixed now. Let me know if there is still an issue on your side.
