### ISSUE TITLE
Nuget updates demands nugets that do not exist on nuget.org yet

### ISSUE THREAD

**Issue by Marc-Antoine-Soucy** [unoplatform/uno.extensions#974]
## Current behavior

When updating the nugets to 2.3.0-dev.389, and trying to run the app you get the exception 
 error NU1101: Unable to find package Uno.Extensions.Toolkit.WinUI. No packages exist with this id in source(s): C:\Program Files\dotnet\library-packs, Microsoft Visual Studio Offline Packages, nuget.org, nventive

![image](https://user-images.githubusercontent.com/90481654/206248238-efefe127-eb15-408f-95f3-f6c741d58a45.png)
https://www.nuget.org/packages?q=Uno.Extensions.Toolkit.WinUI
## Expected behavior
You should be able to get that nuget.

## How to reproduce it (as minimally and precisely as possible)
Make an app that uses the nuget uno.extensions and update to 2.3.0-dev.389. Notice that you cant find the Uno.Extensions.Toolkit.WinUI nuget

## Environment

Nuget Package:
uno.extensions
Package Version(s):
2.3.0-dev.389
Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [X] 2022 (version: 17.4.1)
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by nickrandolph** [comment]
This should be fixed now - new packages should be available eg https://www.nuget.org/packages/Uno.Extensions.Toolkit.WinUI/2.3.0-dev.394
