### ISSUE TITLE
[Navigation][Android] Default section takes too much time before appearing on first navigation

### ISSUE THREAD

**Issue by takla21** [unoplatform/uno.extensions#976]
## Current behavior

![ezgif com-gif-maker](https://user-images.githubusercontent.com/17461593/206344033-933c224f-9f36-4a8f-8c6a-9b5fc27c35c8.gif)

When navigating on a page with multiple sections, there's a delay before the default section is starting to appear. In the gif, you can see the background of the main page (in orange).

## Expected behavior

The default section should appear right away.

## How to reproduce it (as minimally and precisely as possible)

- Download this sample [SectionNavPerf.zip](https://github.com/unoplatform/uno.extensions/files/10181711/SectionNavPerf.zip)
- Deploy on Android
- Navigate to main page

## Environment

Nuget Package: uno.extensions.navigation

Package Version(s): 2.3.0-dev.376

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [x] 2022 (version: 17.3.5)
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

It can get worse the more the section page is more complexe.

**Comment by jeromelaban** [comment]
Does it happen when running with AOT on device?

**Comment by takla21** [comment]
I was able to confirm that the bug is mostly on Android. I've updated the title and description.

@jeromelaban I'll try to run the sample with AOT. Although if it can help, on our app we tried it with profiled aot (profiled with that part) and it didn't help

**Comment by jeromelaban** [comment]
Note that profiled AOT on Android does not do much if running on net6+. You'll need a full AOT build to see any difference.

**Comment by takla21** [comment]
@jeromelaban the bug still happens with full AOT

![aot](https://user-images.github

Here's the sample with full aot
[SectionNavPerf_AOT.zip](https://github.com/unoplatform/uno.extensions/files/10190651/SectionNavPerf_AOT.zip)
usercontent.com/17461593/206590851-84c25c4c-8e5a-4cee-a38f-1adc422c18ab.gif)

**Comment by nickrandolph** [comment]
I'll take a look to see why it's defaulting to the reflection based routing - something is causing it to iterate through the assembly and use reflection to pair views and viewmodels. If Logging is enabled, there should be a message about the use of reflection in the log

**Comment by nickrandolph** [comment]
We've done a couple of passes on improving this, so am going to close this item
