### ISSUE TITLE
[ListFeed][Android][IOS][Regression] When updating Listfeed, UI issues popup

### ISSUE THREAD

**Issue by Marc-Antoine-Soucy** [unoplatform/uno.extensions#977]
## Current behavior

When updating the listfeed, we get a lot of weird UI things happening. For example, on android, a bottom navbar text gets it's color changed, the item being updated could take more than 5 seconds to reload, a togglebutton loses it's other image so when you click on it, it becomes invisible. On IOS, all of the info sometimes just disappears instead of being updated.

## Expected behavior
These thing should not happen, it should be smooth like it was in the past.

## How to reproduce it (as minimally and precisely as possible)

I tried to make a repro app in the basic 
[App10.zip](https://github.com/unoplatform/uno.extensions/files/10181863/App10.zip)
And then I tried to make a repro with the extension app, and I think it could have worked, but I got this issue:
https://github.com/unoplatform/uno.extensions/discussions/972
And I also couldnt update some packages which blocked me from updating the packages that would allow me to reproduce the issue.
[feedViewIssues.zip](https://github.com/unoplatform/uno.extensions/files/10181997/feedViewIssues.zip)

I have a branch of an app that you can easily see the issue on. (de/maso/uno)
## Environment

Nuget Package:
Uno.Extensions 
Package Version(s):
2.3.0-dev.376
Affected platform(s):

- [X] iOS
- [X] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [X] 2022 (version: 17.4.1)
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by dr1rrb** [comment]
Closed by #1000
