### ISSUE TITLE
[Navigation][iOS] Attempt to drag drop move the whole list down when in a page navigated with uno.extension navigation recipe

### ISSUE THREAD

**Issue by Marc-Antoine-Soucy** [unoplatform/uno.extensions#997]
## Current behavior
![dragdropios](https://user-images.githubusercontent.com/90481654/207935950-1b38b6e0-10d4-4603-87dd-754c3495d4b5.gif)

The whole list goes down instead of the item.

## Expected behavior
![dragdropdroid](https://user-images.githubusercontent.com/90481654/207935969-59731c61-00fd-45ea-bd74-fb2739f55e57.gif)
![dragdropdropWinui](https://user-images.githubusercontent.com/90481654/207935981-93c25212-8c01-48c0-88aa-58f862bb5f57.gif)

Only the items you are trying to drag should move, just like on WinUI or Android

## How to reproduce it (as minimally and precisely as possible)

In the constructor of the ViewModel:
`HOSObservableCollection = new ObservableCollection<string>(new string[] { "STRING1! AAAAA", "STRING2! BBBBB", "STRING3! CCCCC" });`

in the viewmodel
    `public ObservableCollection<string> HOSObservableCollection { get; }`

In the xaml:
```
<ListView ItemsSource="{Binding HOSObservableCollection}"
          SelectionMode="Single"
          AllowDrop="True"
          CanDragItems="True"
          CanReorderItems="True"
          Padding="16,0"
          Grid.Row="0">
    <ListView.ItemTemplate>
        <DataTemplate>
            <Grid MinHeight="120">
                <TextBlock Text="{Binding}"
                           FontSize="60"
                           VerticalAlignment="Center"/>
            </Grid>
        </DataTemplate>
    </ListView.ItemTemplate>
    <ListView.ItemContainerStyle>
        <Style TargetType="ListViewItem">
            <Setter Property="Background"
                    Value="Transparent" />
            <Setter Property="Template">
                <Setter.Value>
                    <ControlTemplate TargetType="ListViewItem">
                        <Grid x:Name="RootContent"
	                           VerticalAlignment="Center"
	                           BorderBrush="Black"
                               Margin="12"
	                           BorderThickness="1"
	                           Background="Red"
	                           CornerRadius="10">

                            <ContentPresenter x:Name="ContentPresenter"
                                              Content="{TemplateBinding Content}"
                                              ContentTemplate="{TemplateBinding ContentTemplate}"
                                              xamarin:ContentTemplateSelector="{TemplateBinding ContentTemplateSelector}" />
                        </Grid>
                    </ControlTemplate>
                </Setter.Value>
            </Setter>
        </Style>
    </ListView.ItemContainerStyle>
    <ListView.ItemsPanel>
        <ItemsPanelTemplate>
            <ItemsStackPanel Orientation="Vertical" />
        </ItemsPanelTemplate>
    </ListView.ItemsPanel>
</ListView>
```

[DragDRopping.zip](https://github.com/unoplatform/uno.extensions/files/10239653/DragDRopping.zip)

## Environment
Extensions

Nuget Package:

I've tried with these nuggets on another app, and the issue is still present. 
Extensions: "2.3.0-dev.402"
"Uno.WinUI" Version="4.7.0-dev.626" 

On the sample: 

Extensions: "2.2.0"
"Uno.WinUI" Version="4.6.19" 
Package Version(s):

Affected platform(s):

- [X] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [X] 2022 (version: 17.4.1)
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

It doesnt happen on the basic Uno Template

**Comment by takla21** [comment]
I've been told that this issue may need more information. As stated at the end of OP, we can't reproduce this issue outside of an uno extension environment sample. However, I tried to investigate this a bit further, mostly by simplifying the previous sample as much as I could (See new sample below). 

I think that it may be related to how to page is being displayed with the uno.extension navigator recipe, because of those two reason
- It's not simply because the page is in a frame. I tried it on an sample without uno.extension
- On the new sample, I've removed most of the other uno.extension nuget packages except of the one that navigation needs and the issue still happens. (Even on latest version **2.3.0-dev.448** )

[DragDRopping_simplify.zip](https://github.com/unoplatform/uno.extensions/files/10340225/DragDRopping_simplify.zip)

@nickrandolph @dr1rrb Any ideas?

**Comment by nickrandolph** [comment]
In the provided samples I've removed anything related to uno.extensions.navigation and I'm still seeing the issue, so I'm pretty confident that this isn't related to the use of navigation. 
I'll comment back when I know more about what's going on with iOS

**Comment by nickrandolph** [comment]
[DragDropping.zip](https://github.com/unoplatform/uno.extensions/files/10358468/DragDropping.zip)

I've updated the sample to use simple Frame.Navigate and I've updated to the latest uno dev release and the issue still exists.
@dr1rrb @ajpinedam do either of you have an idea on this - I'm seeing some pointer related events in the output window that might make more sense to you.

**Comment by dr1rrb** [comment]
No specific idea on this for now ... but I noticed that we have multiple SV issues on this project (including `ItemsRepeater` issues as they are usually linked to the `UIElement.ViewportUpdated` event which is deeply impacted by SV), we should probably consider all of them at once. I'll try to have a look after my current `IR` issue ... if not related.

**Comment by takla21** [comment]
Any updates on this?
